// Sprint: #148; Story: #31; Story-ID: 7a1175a64d88
// Product diagnostic parsing and original-position remapping. Parsing keeps
// upstream errorcheck's message grouping (a tab-indented line continues the
// previous message) but classifies every message: positioned on a known
// generated file, autogenerated, or unpositioned. Remapping is all-or-nothing.
package main

import (
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// diagnostic is one product message. Text is everything after the position
// prefix, including continuation lines, which is what ERROR regexps see.
type diagnostic struct {
	Raw  string `json:"raw"`
	Kind string `json:"kind"` // positioned | autogenerated | unpositioned
	File string `json:"file,omitempty"`
	Line int    `json:"line,omitempty"`
	Col  int    `json:"column,omitempty"`
	Text string `json:"text"`
	// Original is set once the diagnostic has been remapped.
	Original *position `json:"original,omitempty"`
	// Remapped is the diagnostic as it reads on the original source.
	Remapped string `json:"remapped,omitempty"`
	// MappingStatus is mapped, autogenerated, unmapped, ambiguous, or
	// unpositioned. Failed records remain in the response as evidence.
	MappingStatus string `json:"mapping_status"`
	MappingError  string `json:"mapping_error,omitempty"`
}

// positionRx matches "file:line[:col]: text". The file part may not contain
// spaces or colons: a message that does not fit is unpositioned, never a
// silently accepted match.
var positionRx = regexp.MustCompile(`(?s)\A([^\s:]+):(\d+)(?::(\d+))?: (.*)\z`)

var autogeneratedRx = regexp.MustCompile(`(?s)\A<autogenerated>:(\d+)(?::(\d+))?: (.*)\z`)

const autogenerated = "<autogenerated>"

// replacePrefix rewrites one compile-time path to its diagnostic short name
// wherever it starts a token (upstream errorcheck's helper, verbatim).
func replacePrefix(s, old, new string) string {
	if !strings.Contains(s, old) {
		return s
	}
	s = strings.ReplaceAll(s, " "+old, " "+new)
	s = strings.ReplaceAll(s, "\n"+old, "\n"+new)
	s = strings.ReplaceAll(s, "\n\t"+old, "\n\t"+new)
	if strings.HasPrefix(s, old) {
		s = new + s[len(old):]
	}
	return s
}

// splitMessages groups product output into messages exactly as upstream
// errorcheck does: tab-indented lines continue the previous message, blank
// lines are dropped, and a trailing carriage return is stripped.
func splitMessages(out string) []string {
	var res []string
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSuffix(line, "\r")
		if strings.HasPrefix(line, "\t") {
			if len(res) == 0 {
				res = append(res, line)
				continue
			}
			res[len(res)-1] += "\n" + line
		} else if strings.TrimSpace(line) != "" {
			res = append(res, line)
		}
	}
	return res
}

// parseDiagnostics classifies every message of the captured output.
func parseDiagnostics(out string) []diagnostic {
	var res []diagnostic
	for _, msg := range splitMessages(out) {
		d := diagnostic{Raw: msg, Kind: "unpositioned", Text: msg}
		if m := autogeneratedRx.FindStringSubmatch(msg); m != nil {
			line, err1 := strconv.Atoi(m[1])
			col, err2 := 0, error(nil)
			if m[2] != "" {
				col, err2 = strconv.Atoi(m[2])
			}
			if err1 == nil && err2 == nil && line > 0 && (m[2] == "" || col > 0) {
				d.Kind, d.File, d.Line, d.Col, d.Text = "autogenerated", autogenerated, line, col, m[3]
			}
		} else if m := positionRx.FindStringSubmatch(msg); m != nil {
			line, err1 := strconv.Atoi(m[2])
			col, err2 := 0, error(nil)
			if m[3] != "" {
				col, err2 = strconv.Atoi(m[3])
			}
			if err1 == nil && err2 == nil && line > 0 && (m[3] == "" || col > 0) {
				d.Kind, d.File, d.Line, d.Col, d.Text = "positioned", m[1], line, col, m[4]
			}
		}
		res = append(res, d)
	}
	return res
}

// remapAll rewrites every positioned diagnostic onto its original position,
// including position references inside the message text. Autogenerated
// diagnostics pass through unchanged. Any unpositioned message, any position
// on a file the maps do not cover, and any generated line the map does not
// record fails the whole remap: nothing is guessed or dropped.
func (r *remapper) remapAll(diags []diagnostic) ([]diagnostic, error) {
	var errs []string
	out := make([]diagnostic, 0, len(diags))
	for _, d := range diags {
		switch d.Kind {
		case "autogenerated":
			d.Remapped = d.Raw
			d.MappingStatus = "autogenerated"
		case "positioned":
			p, err := r.remap(d.File, d.Line, d.Col)
			if err != nil {
				d.MappingStatus = "unmapped"
				if strings.Contains(err.Error(), "ambiguous") {
					d.MappingStatus = "ambiguous"
				}
				d.MappingError = err.Error()
				errs = append(errs, fmt.Sprintf("%s: %s", err.Error(), d.Raw))
				out = append(out, d)
				continue
			}
			text, err := r.remapReferences(d.Text)
			if err != nil {
				d.MappingStatus = "unmapped"
				if strings.Contains(err.Error(), "ambiguous") {
					d.MappingStatus = "ambiguous"
				}
				d.MappingError = err.Error()
				errs = append(errs, fmt.Sprintf("%s: %s", err.Error(), d.Raw))
				out = append(out, d)
				continue
			}
			original := p
			d.Original, d.Text, d.Remapped = &original, text, p.String()+": "+text
			d.MappingStatus = "mapped"
		default:
			d.MappingStatus = "unpositioned"
			d.MappingError = "product output has no recognized position"
			errs = append(errs, "unpositioned product output: "+d.Raw)
			out = append(out, d)
			continue
		}
		out = append(out, d)
	}
	if len(errs) > 0 {
		return out, errors.New("remap failed closed:\n\t" + strings.Join(errs, "\n\t"))
	}
	return out, nil
}

// remapReferences rewrites generated-file position references embedded in a
// message body. A reference the map cannot resolve fails the message.
func (r *remapper) remapReferences(text string) (string, error) {
	rx := r.referenceRx()
	var b strings.Builder
	last := 0
	for _, idx := range rx.FindAllStringSubmatchIndex(text, -1) {
		file := text[idx[2]:idx[3]]
		line, _ := strconv.Atoi(text[idx[4]:idx[5]])
		col := 0
		if idx[6] >= 0 {
			col, _ = strconv.Atoi(text[idx[6]:idx[7]])
		}
		p, err := r.remap(file, line, col)
		if err != nil {
			return "", fmt.Errorf("embedded reference %s", err.Error())
		}
		b.WriteString(text[last:idx[2]])
		b.WriteString(p.String())
		last = idx[1]
	}
	b.WriteString(text[last:])
	return b.String(), nil
}
