// Sprint: #148; Story: #31; Story-ID: 7a1175a64d88
package main

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const fixtureDir = "../../../tests/corpus/fixtures/source-map"

// synthetic lowered unit: two original files, one generated file, every
// marker position recorded. Line numbers are load-bearing for the tests.
const (
	caseA = "package p\n\nfunc f() {\n\tvar unused int // ERROR \"declared and not used: unused\"\n\tg()\n}\n"
	caseB = "package p\n\nfunc g() {\n\tvar x = 1 // ERROR \"x declared and not used\" \"other message\"\n}\n"
	gen   = "// Code generated by mvdan.cc/sh/v3/lower. DO NOT EDIT.\npackage p\n\n" +
		"// lower:0\nfunc f() {\n\t// lower:1\n\tvar unused int\n\t// lower:2\n\tg()\n}\n\n" +
		"// lower:3\nfunc g() {\n\t// lower:4\n\tvar x = 1\n}\n"
)

type entry struct {
	goLine int
	file   string
	offset int
	node   string
}

var genEntries = []entry{
	{5, "a.go", strings.Index(caseA, "func f"), "BashPPFuncDecl"},
	{7, "a.go", strings.Index(caseA, "var unused"), "BashPPVarDecl"},
	{9, "a.go", strings.Index(caseA, "g()"), "BashPPCall"},
	{13, "b.go", strings.Index(caseB, "func g"), "BashPPFuncDecl"},
	{15, "b.go", strings.Index(caseB, "var x"), "BashPPVarDecl"},
}

// buildMap serializes a map the way the lowerer's CLI does, from ordered
// sources and explicit generated-line → original-offset entries.
func buildMap(generated string, sources [][2]string, entries []entry) map[string]any {
	lines := strings.Split(generated, "\n")
	base := 0
	bases := map[string]int{}
	var srcs []map[string]any
	for _, s := range sources {
		bases[s[0]] = base
		srcs = append(srcs, map[string]any{"name": s[0], "sha256": digest([]byte(s[1])), "size": len(s[1]), "base": base})
		base += len(s[1]) + 1
	}
	content := map[string]string{}
	for _, s := range sources {
		content[s[0]] = s[1]
	}
	var mappings []map[string]any
	for _, e := range entries {
		line := lines[e.goLine-1]
		prefix := content[e.file][:e.offset]
		mappings = append(mappings, map[string]any{
			"go_line": e.goLine, "go_col": len(line) - len(strings.TrimLeft(line, "\t ")) + 1,
			"source_line": strings.Count(prefix, "\n") + 1, "source_col": e.offset - (strings.LastIndex(prefix, "\n") + 1) + 1,
			"source_offset": e.offset + bases[e.file], "node": e.node, "source_file": e.file, "source_file_offset": e.offset,
		})
	}
	if mappings == nil {
		mappings = []map[string]any{}
	}
	return map[string]any{"schema_version": mapSchemaVersion, "origin": sources[0][0], "go_digest": "sha256:" + digest([]byte(generated)),
		"mappings": mappings, "source_kind": mapSourceKind, "front_end": mapFrontEnd, "sources": srcs}
}

func syntheticSources() map[string]sourceBytes {
	return map[string]sourceBytes{"a.go": {SHA256: digest([]byte(caseA)), Data: []byte(caseA)}, "b.go": {SHA256: digest([]byte(caseB)), Data: []byte(caseB)}}
}

func syntheticMap(t *testing.T, mutate func(map[string]any)) *sourceMap {
	t.Helper()
	raw := buildMap(gen, [][2]string{{"a.go", caseA}, {"b.go", caseB}}, genEntries)
	if mutate != nil {
		mutate(raw)
	}
	data, err := json.Marshal(raw)
	if err != nil {
		t.Fatal(err)
	}
	m, err := decodeSourceMap(data)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	return m
}

func syntheticRemapper(t *testing.T) *remapper {
	t.Helper()
	m := syntheticMap(t, nil)
	if err := validateSourceMap(m, []byte(gen), digest([]byte(gen)), syntheticSources()); err != nil {
		t.Fatalf("synthetic map rejected: %v", err)
	}
	r := newRemapper()
	if err := r.add("gen.go", m, map[string]string{"a.go": "a.go", "b.go": "b.go"}); err != nil {
		t.Fatal(err)
	}
	return r
}

func TestRetainedProductMapValidatesAndEveryMutationRejects(t *testing.T) {
	mapBytes, err := os.ReadFile(filepath.Join(fixtureDir, "functions.map.json"))
	if err != nil {
		t.Fatal(err)
	}
	generated, err := os.ReadFile(filepath.Join(fixtureDir, "functions.generated.go.txt"))
	if err != nil {
		t.Fatal(err)
	}
	original, err := os.ReadFile("../../../tour/_content/tour/basics/functions.go")
	if err != nil {
		t.Fatal(err)
	}
	var provenance struct{ Generated, Source, Map string }
	provBytes, err := os.ReadFile(filepath.Join(fixtureDir, "provenance.json"))
	if err != nil {
		t.Fatal(err)
	}
	var prov map[string]any
	if err := json.Unmarshal(provBytes, &prov); err != nil {
		t.Fatal(err)
	}
	provenance.Generated, provenance.Source, provenance.Map = prov["generated_sha256"].(string), prov["source_sha256"].(string), prov["map_sha256"].(string)
	if digest(generated) != provenance.Generated || digest(original) != provenance.Source || digest(mapBytes) != provenance.Map {
		t.Fatal("retained fixture digests drifted from provenance.json")
	}
	const name = "tour/_content/tour/basics/functions.go"
	sources := map[string]sourceBytes{name: {SHA256: digest(original), Data: original}}
	m, err := decodeSourceMap(mapBytes)
	if err != nil {
		t.Fatal(err)
	}
	if err := validateSourceMap(m, generated, digest(generated), sources); err != nil {
		t.Fatalf("retained product map rejected: %v", err)
	}
	r := newRemapper()
	if err := r.add("functions.generated.go", m, map[string]string{name: "functions.go"}); err != nil {
		t.Fatal(err)
	}
	// Generated line 15 (fmt.Println call) is original line 12 column 2.
	p, err := r.remap("functions.generated.go", 15, 2)
	if err != nil || p.String() != "functions.go:12:2" || !p.ColumnExact || p.Node != "BashPPCall" {
		t.Fatalf("remap of the retained call: %+v %v", p, err)
	}
	// Same line, a different column: line-only, never a fabricated column.
	if p, err := r.remap("functions.generated.go", 15, 30); err != nil || p.String() != "functions.go:12" || p.ColumnExact {
		t.Fatalf("inexact column leaked: %+v %v", p, err)
	}
	// Generated line 14 is the `// lower:2` marker itself: unmapped.
	if _, err := r.remap("functions.generated.go", 14, 2); err == nil {
		t.Fatal("marker line remapped")
	}

	mutations := map[string]func(map[string]any){
		"changed_origin":   func(m map[string]any) { m["origin"] = "other.go" },
		"traversal_source": func(m map[string]any) { m["sources"].([]any)[0].(map[string]any)["name"] = "../functions.go" },
		"missing_kind":     func(m map[string]any) { delete(m, "source_kind") },
		"wrong_frontend":   func(m map[string]any) { m["front_end"] = "unknown" },
		"wrong_schema":     func(m map[string]any) { m["schema_version"] = "bashy-transpile-map-v2" },
		"empty_origin":     func(m map[string]any) { m["origin"] = "" },
		"wrong_go_digest":  func(m map[string]any) { m["go_digest"] = "sha256:" + strings.Repeat("0", 64) },
		"duplicate_source": func(m map[string]any) { s := m["sources"].([]any); m["sources"] = append(s, s[0]) },
		"missing_source":   func(m map[string]any) { m["sources"] = []any{} },
		"invalid_source":   func(m map[string]any) { m["sources"].([]any)[0] = nil },
		"changed_base":     func(m map[string]any) { m["sources"].([]any)[0].(map[string]any)["base"] = 1 },
		"noninteger_base":  func(m map[string]any) { m["sources"].([]any)[0].(map[string]any)["base"] = json.RawMessage("0.0") },
		"changed_size": func(m map[string]any) {
			src := m["sources"].([]any)[0].(map[string]any)
			src["size"] = src["size"].(float64) + 1
		},
		"changed_digest": func(m map[string]any) { m["sources"].([]any)[0].(map[string]any)["sha256"] = strings.Repeat("0", 64) },
		"wrong_line": func(m map[string]any) {
			e := m["mappings"].([]any)[0].(map[string]any)
			e["source_line"] = e["source_line"].(float64) + 1
		},
		"wrong_column": func(m map[string]any) {
			e := m["mappings"].([]any)[0].(map[string]any)
			e["source_col"] = e["source_col"].(float64) + 1
		},
		"wrong_local_offset": func(m map[string]any) {
			e := m["mappings"].([]any)[0].(map[string]any)
			e["source_file_offset"] = e["source_file_offset"].(float64) + 1
		},
		"wrong_go_position": func(m map[string]any) {
			e := m["mappings"].([]any)[0].(map[string]any)
			e["go_line"] = e["go_line"].(float64) + 1
		},
		"empty_mappings":      func(m map[string]any) { m["mappings"] = []any{} },
		"incomplete_mappings": func(m map[string]any) { l := m["mappings"].([]any); m["mappings"] = l[:len(l)-1] },
		"duplicate_mapping":   func(m map[string]any) { l := m["mappings"].([]any); m["mappings"] = append(l, l[len(l)-1]) },
		"unordered_mappings": func(m map[string]any) {
			l := m["mappings"].([]any)
			for i, j := 0, len(l)-1; i < j; i, j = i+1, j-1 {
				l[i], l[j] = l[j], l[i]
			}
		},
		"unknown_source_file": func(m map[string]any) { m["mappings"].([]any)[0].(map[string]any)["source_file"] = "other.go" },
		"empty_node":          func(m map[string]any) { m["mappings"].([]any)[0].(map[string]any)["node"] = "" },
		"fractional_line":     func(m map[string]any) { m["mappings"].([]any)[0].(map[string]any)["go_line"] = 7.5 },
	}
	for name, mutate := range mutations {
		var raw map[string]any
		if err := json.Unmarshal(mapBytes, &raw); err != nil {
			t.Fatal(err)
		}
		mutate(raw)
		data, err := json.Marshal(raw)
		if err != nil {
			t.Fatal(err)
		}
		m, err := decodeSourceMap(data)
		if err == nil {
			err = validateSourceMap(m, generated, digest(generated), sources)
		}
		if err == nil {
			t.Errorf("%s: mutated map accepted", name)
		}
	}
	// Same-size byte mutations with stale metadata: the actual bytes decide.
	if err := validateSourceMap(m, []byte(strings.Replace(string(generated), "func add", "func bad", 1)), digest(generated), sources); err == nil {
		t.Error("generated mutation with a stale record accepted")
	}
	tampered := map[string]sourceBytes{name: {SHA256: digest(original), Data: []byte(strings.Replace(string(original), "func add", "func bad", 1))}}
	if err := validateSourceMap(m, generated, digest(generated), tampered); err == nil {
		t.Error("original mutation with a stale record accepted")
	}
	if err := validateSourceMap(m, generated, digest(generated), map[string]sourceBytes{}); err == nil {
		t.Error("map without retained originals accepted")
	}
	if err := validateSourceMap(m, generated, digest(generated), map[string]sourceBytes{"functions.go": sources[name]}); err == nil {
		t.Error("map with a differently named original accepted")
	}
}

func TestEmptyPackageMapWithTwoSources(t *testing.T) {
	mapBytes, _ := os.ReadFile(filepath.Join(fixtureDir, "empty.map.json"))
	generated, _ := os.ReadFile(filepath.Join(fixtureDir, "empty.generated.go.txt"))
	a, _ := os.ReadFile(filepath.Join(fixtureDir, "empty-a.go"))
	b, _ := os.ReadFile(filepath.Join(fixtureDir, "empty-b.go"))
	sources := map[string]sourceBytes{"empty-a.go": {SHA256: digest(a), Data: a}, "empty-b.go": {SHA256: digest(b), Data: b}}
	m, err := decodeSourceMap(mapBytes)
	if err != nil {
		t.Fatal(err)
	}
	if err := validateSourceMap(m, generated, digest(generated), sources); err != nil {
		t.Fatalf("empty package map rejected: %v", err)
	}
	r := newRemapper()
	if err := r.add("empty.go", m, map[string]string{"empty-a.go": "empty-a.go", "empty-b.go": "empty-b.go"}); err != nil {
		t.Fatal(err)
	}
	// An empty map remaps nothing: every generated position is unmapped.
	if _, err := r.remap("empty.go", 4, 1); err == nil {
		t.Fatal("unmapped position resolved from an empty map")
	}
}

func TestMarkerContractRejectsMalformedGeneratedFiles(t *testing.T) {
	for name, generated := range map[string]string{
		"dangling_marker":  "package p\n// lower:0\n",
		"malformed_marker": "package p\n// lower:x\nfunc f() {}\n",
		"marker_suffix":    "package p\n// lower:0 extra\nfunc f() {}\n",
	} {
		if _, err := expectedPositions([]byte(generated)); err == nil {
			t.Errorf("%s accepted", name)
		}
	}
	positions, err := expectedPositions([]byte("package p\n\n// lower:0\n// lower:1\n\n\tfunc f() {}\n"))
	if err != nil || len(positions) != 1 || positions[0] != [2]int{6, 2} {
		t.Fatalf("consecutive markers name one position: %v %v", positions, err)
	}
}

func TestSourceMapDecoderRejectsTrailingJSON(t *testing.T) {
	raw, err := json.Marshal(buildMap(gen, [][2]string{{"a.go", caseA}, {"b.go", caseB}}, genEntries))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := decodeSourceMap(append(raw, []byte(` {}`)...)); err == nil {
		t.Fatal("source map with trailing JSON accepted")
	}
}

func TestRemapperRejectsAmbiguity(t *testing.T) {
	r := syntheticRemapper(t)
	m := syntheticMap(t, nil)
	shorts := map[string]string{"a.go": "a.go", "b.go": "b.go"}
	if err := r.add("gen.go", m, shorts); err == nil || !strings.Contains(err.Error(), "ambiguous") {
		t.Fatalf("second map for the same generated name accepted: %v", err)
	}
	if err := r.add("a.go", m, shorts); err == nil || !strings.Contains(err.Error(), "ambiguous") {
		t.Fatalf("generated name colliding with an original accepted: %v", err)
	}
	if err := r.add("gen2.go", m, map[string]string{"a.go": "b.go", "b.go": "a.go"}); err == nil || !strings.Contains(err.Error(), "ambiguous") {
		t.Fatalf("renamed originals accepted: %v", err)
	}
	if err := r.add("gen2.go", m, map[string]string{"a.go": "a.go"}); err == nil {
		t.Fatal("missing short name accepted")
	}
	if err := newRemapper().add("gen.go", m, map[string]string{"a.go": "same.go", "b.go": "same.go"}); err == nil || !strings.Contains(err.Error(), "ambiguous") {
		t.Fatalf("two originals sharing one short name accepted: %v", err)
	}
	if _, err := r.remap("other.go", 5, 1); err == nil {
		t.Fatal("unknown generated file remapped")
	}
	if _, err := r.remap("gen.go", 6, 2); err == nil {
		t.Fatal("marker line remapped")
	}
	if _, err := r.remap("gen.go", 2, 1); err == nil {
		t.Fatal("generated-only line remapped")
	}
}

func TestOriginalClaimWithMultipleTargetsIsAmbiguous(t *testing.T) {
	entries := append([]entry(nil), genEntries...)
	entries[3].offset = strings.Index(caseB, "var x") + 4
	m := syntheticMap(t, func(raw map[string]any) {
		other := buildMap(gen, [][2]string{{"a.go", caseA}, {"b.go", caseB}}, entries)
		for key := range raw {
			delete(raw, key)
		}
		for key, value := range other {
			raw[key] = value
		}
	})
	if err := validateSourceMap(m, []byte(gen), digest([]byte(gen)), syntheticSources()); err != nil {
		t.Fatal(err)
	}
	r := newRemapper()
	if err := r.add("gen.go", m, map[string]string{"a.go": "a.go", "b.go": "b.go"}); err != nil {
		t.Fatal(err)
	}
	if _, err := r.remap("b.go", 4, 0); err == nil || !strings.Contains(err.Error(), "ambiguous") {
		t.Fatalf("ambiguous line-only original claim accepted: %v", err)
	}
	if got, err := r.remapAll(parseDiagnostics("b.go:4: ambiguous claim\n")); err == nil || len(got) != 1 || got[0].MappingStatus != "ambiguous" || got[0].Raw == "" {
		t.Fatalf("ambiguous diagnostic was not retained: %+v %v", got, err)
	}
	if p, err := r.remap("b.go", 4, 2); err != nil || !p.ColumnExact {
		t.Fatalf("unique exact-column claim rejected: %+v %v", p, err)
	}
}

func TestRemapAllIsAllOrNothing(t *testing.T) {
	r := syntheticRemapper(t)
	out, err := r.remapAll(parseDiagnostics("gen.go:7:6: declared and not used: unused\n\tcontinuation\ngen.go:15:6: x declared and not used\n<autogenerated>:1: inlining call to g\n"))
	if err != nil {
		t.Fatalf("clean remap failed: %v", err)
	}
	want := []string{"a.go:4: declared and not used: unused\n\tcontinuation", "b.go:4: x declared and not used", "<autogenerated>:1: inlining call to g"}
	for i, d := range out {
		if d.Remapped != want[i] {
			t.Errorf("remapped[%d] = %q, want %q", i, d.Remapped, want[i])
		}
	}
	if out[0].Original.Line != 4 || out[0].Original.ColumnExact || out[0].Original.Node != "BashPPVarDecl" {
		t.Errorf("original position metadata: %+v", out[0].Original)
	}
	exact, err := r.remapAll(parseDiagnostics("gen.go:9:2: undefined: g\n"))
	if err != nil || exact[0].Remapped != "a.go:5:2: undefined: g" {
		t.Fatalf("exact column remap: %+v %v", exact, err)
	}
	// A //line-claimed original position is verified against the map, never trusted.
	claimed, err := r.remapAll(parseDiagnostics("a.go:4:2: declared and not used: unused\na.go:4:9: line-only claim\n"))
	if err != nil || claimed[0].Remapped != "a.go:4:2: declared and not used: unused" || !claimed[0].Original.Verified || !claimed[0].Original.ColumnExact {
		t.Fatalf("verified claim: %+v %v", claimed, err)
	}
	if claimed[1].Remapped != "a.go:4: line-only claim" || claimed[1].Original.ColumnExact {
		t.Fatalf("claim with an unrecorded column: %+v", claimed[1])
	}
	// Embedded references remap too, and fail closed when unmapped.
	ref, err := r.remapAll(parseDiagnostics("gen.go:15:6: x redeclared\n\tprevious declaration at gen.go:7:6\n"))
	if err != nil || ref[0].Remapped != "b.go:4: x redeclared\n\tprevious declaration at a.go:4" {
		t.Fatalf("embedded reference remap: %+v %v", ref, err)
	}
	for name, text := range map[string]string{
		"unmapped_line":       "gen.go:7:6: ok\ngen.go:8:2: on a marker line\n",
		"unknown_file":        "gen.go:7:6: ok\nother.go:7:6: unknown\n",
		"unpositioned":        "gen.go:7:6: ok\n# command-line-arguments\n",
		"leading_tab":         "\tstray continuation\n",
		"signal":              "gen.go:7:6: ok\ngo tool compile: signal: killed\n",
		"embedded_unmapped":   "gen.go:7:6: see gen.go:2:1\n",
		"unverified_claim":    "a.go:2:1: package clause is not a lowering target\n",
		"unverified_ref":      "gen.go:7:6: see a.go:2:1\n",
		"spaces_in_file_name": "my gen.go:7:6: ok\n",
		"zero_column":         "gen.go:7:0: invalid column\n",
		"malformed_auto":      "<autogenerated>bogus inlining call\n",
		"zero_auto_line":      "<autogenerated>:0: inlining call\n",
	} {
		got, err := r.remapAll(parseDiagnostics(text))
		if err == nil {
			t.Errorf("%s: remap did not fail closed: %q", name, text)
		}
		if len(got) == 0 || got[len(got)-1].MappingStatus == "" || got[len(got)-1].MappingError == "" {
			t.Errorf("%s: failed diagnostic was not retained: %+v", name, got)
		}
	}
	if out, err := r.remapAll(nil); err != nil || len(out) != 0 {
		t.Fatalf("empty output remap: %v %v", out, err)
	}
}

func remapped(t *testing.T, text string) []diagnostic {
	t.Helper()
	out, err := syntheticRemapper(t).remapAll(parseDiagnostics(text))
	if err != nil {
		t.Fatalf("remap: %v", err)
	}
	return out
}

func wanted(t *testing.T) []annotation {
	t.Helper()
	a, err := annotations([]byte(caseA), "a.go")
	if err != nil {
		t.Fatal(err)
	}
	b, err := annotations([]byte(caseB), "b.go")
	if err != nil {
		t.Fatal(err)
	}
	return append(a, b...)
}

func TestExactMultiplicityMatch(t *testing.T) {
	want := wanted(t)
	if len(want) != 3 {
		t.Fatalf("annotations: %v", want)
	}
	complete := "gen.go:7:6: declared and not used: unused\ngen.go:15:6: x declared and not used\ngen.go:15:6: other message\n"
	res := matchDiagnostics(want, remapped(t, complete))
	if !res.complete() || res.Matched != 3 || len(res.Pairs) != 3 {
		t.Fatalf("complete match rejected: %+v", res)
	}
	// Order independence: the two b.go annotations are assigned, not consumed greedily.
	reordered := "gen.go:15:6: other message\ngen.go:15:6: x declared and not used\ngen.go:7:6: declared and not used: unused\n"
	if res := matchDiagnostics(want, remapped(t, reordered)); !res.complete() {
		t.Fatalf("reordered complete match rejected: %+v", res)
	}
	cases := map[string]struct {
		text           string
		missing, extra int
	}{
		"one_missing":            {"gen.go:7:6: declared and not used: unused\ngen.go:15:6: x declared and not used\n", 1, 0},
		"all_missing":            {"", 3, 0},
		"one_extra_same_message": {complete + "gen.go:15:6: other message\n", 0, 1},
		"duplicate_absorbed":     {"gen.go:7:6: declared and not used: unused\ngen.go:7:6: declared and not used: unused\ngen.go:15:6: x declared and not used\ngen.go:15:6: other message\n", 0, 1},
		"wrong_line":             {"gen.go:9:2: declared and not used: unused\ngen.go:15:6: x declared and not used\ngen.go:15:6: other message\n", 1, 1},
		"wrong_text":             {"gen.go:7:6: undefined: unused\ngen.go:15:6: x declared and not used\ngen.go:15:6: other message\n", 1, 1},
		"one_matches_two":        {"gen.go:7:6: declared and not used: unused\ngen.go:15:6: x declared and not used\ngen.go:15:6: x declared and not used\n", 1, 1},
		"auto_without_errorauto": {complete + "<autogenerated>:1: inlining call to g\n", 0, 1},
	}
	for name, c := range cases {
		res := matchDiagnostics(want, remapped(t, c.text))
		if res.complete() || len(res.Missing) != c.missing || len(res.Extra) != c.extra {
			t.Errorf("%s: missing=%d extra=%d complete=%v (want %d/%d)", name, len(res.Missing), len(res.Extra), res.complete(), c.missing, c.extra)
		}
	}
}

func TestAnnotationGrammar(t *testing.T) {
	src := "package p\n" +
		"var a int // ERROR \"declared at LINE\" \"also LINE+1\"\n" +
		"var b int //// ERROR \"disabled\"\n" +
		"var c int // GC_ERROR \"gc only\"\n" +
		"func f() {} // ERRORAUTO \"can inline\"\n" +
		"var d int // ERROR \"ref LINE-3\"\n"
	got, err := annotations([]byte(src), "x.go")
	if err != nil {
		t.Fatal(err)
	}
	patterns := []string{"declared at x.go:2", "also x.go:3", "gc only", "can inline", "ref x.go:3"}
	if len(got) != len(patterns) {
		t.Fatalf("annotations: %+v", got)
	}
	for i, p := range patterns {
		if got[i].Pattern != p {
			t.Errorf("annotation %d pattern %q, want %q", i, got[i].Pattern, p)
		}
	}
	if !got[3].Auto || got[2].Auto {
		t.Error("ERRORAUTO/GC_ERROR classification")
	}
	if _, err := annotations([]byte("var x int // ERROR unquoted\n"), "x.go"); err == nil {
		t.Error("unquoted ERROR line accepted")
	}
	if _, err := annotations([]byte("var x int // ERROR \"(\"\n"), "x.go"); err == nil {
		t.Error("invalid regexp accepted")
	}
}

func TestDiagnosticTextAndRegexpAreWholeText(t *testing.T) {
	if !matchDiagnosticText("undefined: x", "undefined: x") || matchDiagnosticText("undefined", "undefined: x") {
		t.Fatal("exact diagnostic text matcher is not exact")
	}
	if ok, err := matchDiagnosticRegexp("undefined: .+", "undefined: x"); err != nil || !ok {
		t.Fatalf("anchored regexp rejected: %v %v", ok, err)
	}
	if ok, err := matchDiagnosticRegexp("undefined", "prefix undefined suffix"); err != nil || ok {
		t.Fatalf("permissive substring regexp accepted: %v %v", ok, err)
	}
	if ok, err := matchDiagnosticRegexp(".*undefined.*", "prefix undefined suffix"); err != nil || !ok {
		t.Fatalf("explicitly permissive regexp rejected: %v %v", ok, err)
	}
}

func TestErrorAutoMatchesOnlyAutogeneratedDiagnostics(t *testing.T) {
	src := "package p\nfunc g() {} // ERRORAUTO \"inlining call to g\"\n"
	want, err := annotations([]byte(src), "a.go")
	if err != nil {
		t.Fatal(err)
	}
	auto := []diagnostic{{Kind: "autogenerated", Text: "inlining call to g", Remapped: "<autogenerated>:1: inlining call to g"}}
	if res := matchDiagnostics(want, auto); !res.complete() {
		t.Fatalf("ERRORAUTO did not consume the autogenerated diagnostic: %+v", res)
	}
	positioned := []diagnostic{{Kind: "positioned", Text: "inlining call to g", Original: &position{File: "a.go", Line: 2}, Remapped: "a.go:2: inlining call to g"}}
	if res := matchDiagnostics(want, positioned); res.complete() {
		t.Fatal("ERRORAUTO consumed a positioned diagnostic")
	}
	if res := matchDiagnostics(want, append(auto, auto...)); res.complete() || len(res.Extra) != 1 {
		t.Fatalf("duplicate autogenerated diagnostic absorbed: %+v", res)
	}
}

func TestExactBytes(t *testing.T) {
	if res := matchBytes([]byte("A\n\nB\n"), []byte("A\n\nB\n")); !res.Equal {
		t.Fatalf("equal bytes rejected: %+v", res)
	}
	if res := matchBytes(nil, nil); !res.Equal {
		t.Fatalf("empty bytes rejected: %+v", res)
	}
	for name, c := range map[string]struct {
		expected, observed, kind string
		offset                   int
	}{
		"missing_newline":  {"A\n", "A", "missing", 1},
		"extra_newline":    {"A", "A\n", "extra", 1},
		"differs":          {"A\n\nB\n", "A\nB\n\n", "differs", 2},
		"crlf":             {"A\n", "A\r\n", "differs", 1},
		"trailing_space":   {"A\n", "A \n", "differs", 1},
		"missing_all":      {"A", "", "missing", 0},
		"extra_all":        {"", "A", "extra", 0},
		"reordered_stream": {"A\nB\n", "B\nA\n", "differs", 0},
	} {
		res := matchBytes([]byte(c.expected), []byte(c.observed))
		if res.Equal || res.Kind != c.kind || res.FirstDifference != c.offset {
			t.Errorf("%s: %+v", name, res)
		}
	}
}

// writeUnit materializes the synthetic unit under dir and returns a request.
func writeUnit(t *testing.T, output string) (request, string) {
	t.Helper()
	dir := t.TempDir()
	write := func(name, data string) fileInput {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(data), 0600); err != nil {
			t.Fatal(err)
		}
		return fileInput{Path: p, SHA256: digest([]byte(data))}
	}
	raw, err := json.Marshal(buildMap(gen, [][2]string{{"a.go", caseA}, {"b.go", caseB}}, genEntries))
	if err != nil {
		t.Fatal(err)
	}
	req := request{EvidenceRoot: dir, Units: []unit{{Generated: write("gen.go", gen), Short: "gen.go", Map: write("gen.go.map", string(raw)),
		Sources: []sourceInput{{fileInput: write("a.go", caseA), Name: "a.go", Short: "a.go"}, {fileInput: write("b.go", caseB), Name: "b.go", Short: "b.go"}}}},
		Output: []fileInput{write("stdout", ""), write("stderr", output)}}
	return req, dir
}

const completeOutput = "gen.go:7:6: declared and not used: unused\ngen.go:15:6: x declared and not used\ngen.go:15:6: other message\n"

func TestCheckEndToEnd(t *testing.T) {
	req, _ := writeUnit(t, completeOutput)
	res, err := check(req)
	if err != nil || res.Verdict != "PASS" || res.Units != 1 || res.Match.Matched != 3 {
		t.Fatalf("complete evidence rejected: %+v %v", res, err)
	}
	if res.Remapped[0].Remapped != "a.go:4: declared and not used: unused" {
		t.Fatalf("remapped diagnostic: %+v", res.Remapped[0])
	}
	for name, text := range map[string]string{
		"missing":      "gen.go:7:6: declared and not used: unused\ngen.go:15:6: x declared and not used\n",
		"extra":        completeOutput + "gen.go:15:6: other message\n",
		"unmapped":     completeOutput + "gen.go:2:1: package clause\n",
		"unpositioned": completeOutput + "# p\n",
		"auto_extra":   completeOutput + "<autogenerated>:1: inlining call to g\n",
	} {
		req, _ := writeUnit(t, text)
		if res, err := check(req); err == nil || res.Verdict == "PASS" {
			t.Errorf("%s: accepted %q", name, text)
		}
	}
	req, _ = writeUnit(t, completeOutput+"<autogenerated>:1: inlining call to g\n")
	if res, err := check(req); err == nil || res.Verdict == "PASS" {
		t.Fatalf("unexpected autogenerated diagnostic was hidden: %+v %v", res, err)
	}
	// Compile-time paths are rewritten to short names before remapping, as
	// upstream errorcheck does; an alias that is not declared stays unmapped.
	aliased := strings.ReplaceAll(completeOutput, "gen.go:", "/build/x/gen.go:") + "/build/x/gen.go:15:6: x redeclared\n\tprevious declaration at /build/x/gen.go:7:6\n"
	req, _ = writeUnit(t, aliased)
	if res, err := check(req); err == nil || res.Verdict == "PASS" {
		t.Fatal("undeclared compile-time path accepted")
	}
	req.Units[0].Aliases = []string{"/build/x/gen.go"}
	res, err = check(req)
	if err == nil || res.Verdict == "PASS" || len(res.Match.Extra) != 1 || res.Match.Extra[0].Remapped != "b.go:4: x redeclared\n\tprevious declaration at a.go:4" {
		t.Fatalf("aliased remap: %+v %v", res, err)
	}
	req, _ = writeUnit(t, strings.ReplaceAll(completeOutput, "gen.go:", "/build/x/gen.go:"))
	req.Units[0].Aliases = []string{"/build/x/gen.go"}
	if res, err := check(req); err != nil || res.Verdict != "PASS" {
		t.Fatalf("aliased complete evidence rejected: %+v %v", res, err)
	}
	req.Units[0].Aliases = []string{""}
	if _, err := check(req); err == nil {
		t.Fatal("empty alias accepted")
	}
}

func TestCheckFailsClosedOnEvidenceProblems(t *testing.T) {
	req, dir := writeUnit(t, completeOutput)
	if res, err := check(request{}); err == nil || res.Verdict == "PASS" {
		t.Fatal("empty request passed")
	}
	tamper := func(name string, mutate func(*request)) {
		t.Helper()
		req, _ := writeUnit(t, completeOutput)
		mutate(&req)
		if res, err := check(req); err == nil || res.Verdict == "PASS" {
			t.Errorf("%s: accepted", name)
		}
	}
	tamper("map_sha", func(r *request) { r.Units[0].Map.SHA256 = strings.Repeat("0", 64) })
	tamper("generated_bytes", func(r *request) { os.WriteFile(r.Units[0].Generated.Path, []byte(gen+"\n"), 0600) })
	tamper("source_bytes", func(r *request) {
		os.WriteFile(r.Units[0].Sources[0].Path, []byte(strings.Replace(caseA, "not used", "not use", 1)), 0600)
	})
	tamper("output_bytes", func(r *request) { os.WriteFile(r.Output[1].Path, []byte(completeOutput+"\n\n"), 0600) })
	tamper("generated_short_collides", func(r *request) { r.Units[0].Short = "a.go" })
	tamper("unsafe_short", func(r *request) { r.Units[0].Sources[0].Short = "../a.go" })
	tamper("unparseable_short", func(r *request) { r.Units[0].Sources[0].Short = "bad:name.go" })
	tamper("unsafe_generated_short", func(r *request) { r.Units[0].Short = "../gen.go" })
	tamper("duplicate_unit", func(r *request) { r.Units = append(r.Units, r.Units[0]) })
	tamper("ambiguous_alias", func(r *request) {
		r.Units[0].Aliases = []string{"/build/same.go"}
		r.Units[0].Sources[0].Aliases = []string{"/build/same.go"}
	})
	tamper("directory_input", func(r *request) { r.Output[0].Path = dir })
	tamper("half_byte_pair", func(r *request) { r.ExpectedBytes = &r.Output[0] })
	tamper("map_edited_consistently", func(r *request) {
		raw := buildMap(gen, [][2]string{{"a.go", caseA}, {"b.go", caseB}}, genEntries)
		raw["mappings"].([]map[string]any)[1]["source_line"] = 5
		data, _ := json.Marshal(raw)
		os.WriteFile(r.Units[0].Map.Path, data, 0600)
		r.Units[0].Map.SHA256 = digest(data)
	})
	// Byte matching rides alongside diagnostics and fails independently.
	expected := filepath.Join(dir, "expected.out")
	os.WriteFile(expected, []byte("A\n\nB\n"), 0600)
	observed := filepath.Join(dir, "observed.out")
	os.WriteFile(observed, []byte("A\n\nB\n"), 0600)
	req.ExpectedBytes = &fileInput{Path: expected, SHA256: digest([]byte("A\n\nB\n"))}
	req.ObservedBytes = &fileInput{Path: observed, SHA256: digest([]byte("A\n\nB\n"))}
	if res, err := check(req); err != nil || res.Verdict != "PASS" || res.Bytes == nil || !res.Bytes.Equal {
		t.Fatalf("equal bytes rejected: %+v %v", res, err)
	}
	os.WriteFile(observed, []byte("A\nB\n\n"), 0600)
	req.ObservedBytes.SHA256 = digest([]byte("A\nB\n\n"))
	res, err := check(req)
	if err == nil || res.Verdict == "PASS" || res.Bytes == nil || res.Bytes.Kind != "differs" || !strings.Contains(err.Error(), "differs at offset 2") {
		t.Fatalf("reordered bytes accepted: %+v %v", res, err)
	}
}

func TestCheckSupportsByteOnlyObligations(t *testing.T) {
	root := t.TempDir()
	write := func(name, data string) *fileInput {
		path := filepath.Join(root, name)
		if err := os.WriteFile(path, []byte(data), 0600); err != nil {
			t.Fatal(err)
		}
		return &fileInput{Path: path, SHA256: digest([]byte(data))}
	}
	req := request{EvidenceRoot: root, ExpectedBytes: write("expected", "A\n\nB\n"), ObservedBytes: write("observed", "A\n\nB\n")}
	if res, err := check(req); err != nil || res.Verdict != "PASS" || res.Bytes == nil || !res.Bytes.Equal || res.Match != nil {
		t.Fatalf("byte-only equality rejected: %+v %v", res, err)
	}
	if err := os.WriteFile(req.ObservedBytes.Path, []byte("A\nB\n\n"), 0600); err != nil {
		t.Fatal(err)
	}
	req.ObservedBytes.SHA256 = digest([]byte("A\nB\n\n"))
	if res, err := check(req); err == nil || res.Verdict == "PASS" || res.Bytes.Kind != "differs" {
		t.Fatalf("byte-only reordering accepted: %+v %v", res, err)
	}
}

func TestCheckRejectsEvidencePathEscapes(t *testing.T) {
	req, root := writeUnit(t, completeOutput)
	outside := t.TempDir()
	outsideOutput := filepath.Join(outside, "stderr")
	if err := os.WriteFile(outsideOutput, []byte(completeOutput), 0600); err != nil {
		t.Fatal(err)
	}
	req.Output[1] = fileInput{Path: outsideOutput, SHA256: digest([]byte(completeOutput))}
	if _, err := check(req); err == nil || !strings.Contains(err.Error(), "outside evidence_root") {
		t.Fatalf("lexical path escape accepted: %v", err)
	}

	req, root = writeUnit(t, completeOutput)
	link := filepath.Join(root, "outside-link")
	if err := os.Symlink(outside, link); err != nil {
		t.Fatal(err)
	}
	req.Output[1] = fileInput{Path: filepath.Join(link, "stderr"), SHA256: digest([]byte(completeOutput))}
	if _, err := check(req); err == nil || !strings.Contains(err.Error(), "resolves outside evidence_root") {
		t.Fatalf("parent-symlink path escape accepted: %v", err)
	}
}

func TestOutputFilesKeepMessageBoundaryWithoutInventedBytes(t *testing.T) {
	req, root := writeUnit(t, "gen.go:15:6: x declared and not used\ngen.go:15:6: other message")
	first := filepath.Join(root, "stdout")
	if err := os.WriteFile(first, []byte("gen.go:7:6: declared and not used: unused"), 0600); err != nil {
		t.Fatal(err)
	}
	req.Output[0].SHA256 = digest([]byte("gen.go:7:6: declared and not used: unused"))
	if res, err := check(req); err != nil || res.Verdict != "PASS" || len(res.Remapped) != 3 {
		t.Fatalf("independent output message boundaries were merged: %+v %v", res, err)
	}
}

func TestMainRejectsUnknownFieldsAndTrailingData(t *testing.T) {
	if os.Getenv("SOURCE_REMAP_MAIN") != "" {
		main()
		os.Exit(0)
	}
	req, _ := writeUnit(t, completeOutput)
	body, _ := json.Marshal(req)
	for name, stdin := range map[string]string{"good": string(body), "unknown": `{"units":[],"bogus":1}`, "trailing": string(body) + "{}"} {
		out, code := runMain(t, stdin)
		var res response
		if err := json.Unmarshal([]byte(out), &res); err != nil {
			t.Fatalf("%s: non-JSON response %q", name, out)
		}
		if name == "good" && (code != 0 || res.Verdict != "PASS") {
			t.Errorf("good request: exit %d %+v", code, res)
		}
		if name != "good" && (code != 2 || res.Verdict != "FAIL") {
			t.Errorf("%s: exit %d %+v", name, code, res)
		}
	}
	failing, _ := writeUnit(t, completeOutput+"gen.go:2:1: unmapped package line\n")
	body, _ = json.Marshal(failing)
	out, code := runMain(t, string(body))
	var res response
	if err := json.Unmarshal([]byte(out), &res); err != nil {
		t.Fatal(err)
	}
	if code != 1 || res.Verdict != "FAIL" || len(res.Remapped) != 4 || res.Remapped[3].MappingStatus != "unmapped" || res.Remapped[3].Raw == "" {
		t.Fatalf("failed command did not serialize unmapped evidence: exit=%d %+v", code, res)
	}
}

func runMain(t *testing.T, stdin string) (string, int) {
	t.Helper()
	exe, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(exe, "-test.run=TestMainRejectsUnknownFieldsAndTrailingData")
	cmd.Env = append(os.Environ(), "SOURCE_REMAP_MAIN=1")
	cmd.Stdin = strings.NewReader(stdin)
	out, err := cmd.Output()
	code := 0
	if err != nil {
		if exit, ok := err.(interface{ ExitCode() int }); ok {
			code = exit.ExitCode()
		} else {
			t.Fatal(err)
		}
	}
	return strings.TrimSpace(string(out)), code
}
