// Sprint: #148; Story: #31; Story-ID: 7a1175a64d88
// Exact matcher primitives. Diagnostics are matched to ERROR annotations as a
// perfect one-to-one assignment: every annotation consumes exactly one
// diagnostic and every diagnostic is consumed by exactly one annotation.
// Bytes are compared whole. Missing and extra are both failures; there is no
// tolerance and no normalization here. Which recipes get which tolerance is
// diagnostic policy (Sprint 154), layered on top of these primitives.
package main

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

var (
	errRx       = regexp.MustCompile(`// (?:GC_)?ERROR (.*)`)
	errAutoRx   = regexp.MustCompile(`// (?:GC_)?ERRORAUTO (.*)`)
	errQuotesRx = regexp.MustCompile(`"([^"]*)"`)
	lineRx      = regexp.MustCompile(`LINE(([+-])(\d+))?`)
)

// annotation is one quoted regexp of an ERROR line: one expected diagnostic.
type annotation struct {
	File    string `json:"file"`
	Line    int    `json:"line"`
	Pattern string `json:"pattern"`
	Auto    bool   `json:"auto"`
	re      *regexp.Regexp
}

func (a annotation) String() string { return fmt.Sprintf("%s:%d: %#q", a.File, a.Line, a.Pattern) }

// annotations reads `// ERROR "re"...` lines from original source bytes with
// upstream errorcheck's grammar: a `////` line is disabled, LINE±n resolves
// to short:n, and an ERROR line without quoted patterns is an error.
func annotations(src []byte, short string) ([]annotation, error) {
	var res []annotation
	for i, line := range strings.Split(string(src), "\n") {
		lineNum := i + 1
		if strings.Contains(line, "////") {
			continue
		}
		auto := false
		m := errAutoRx.FindStringSubmatch(line)
		if m != nil {
			auto = true
		} else {
			m = errRx.FindStringSubmatch(line)
		}
		if m == nil {
			continue
		}
		mm := errQuotesRx.FindAllStringSubmatch(m[1], -1)
		if mm == nil {
			return nil, fmt.Errorf("%s:%d: invalid errchk line: %s", short, lineNum, line)
		}
		for _, q := range mm {
			rx := lineRx.ReplaceAllStringFunc(q[1], func(s string) string {
				n := lineNum
				if strings.HasPrefix(s, "LINE+") {
					delta, _ := strconv.Atoi(s[5:])
					n += delta
				} else if strings.HasPrefix(s, "LINE-") {
					delta, _ := strconv.Atoi(s[5:])
					n -= delta
				}
				return fmt.Sprintf("%s:%d", short, n)
			})
			// A diagnostic regexp is a whole-text obligation. Callers that
			// intentionally permit a prefix/suffix must say so with .*.
			re, err := regexp.Compile(`\A(?:` + rx + `)\z`)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: invalid regexp %q in ERROR line: %v", short, lineNum, rx, err)
			}
			res = append(res, annotation{File: short, Line: lineNum, Pattern: rx, Auto: auto, re: re})
		}
	}
	return res, nil
}

// pair is one annotation ↔ diagnostic assignment of a complete match.
type pair struct {
	Annotation annotation `json:"annotation"`
	Diagnostic string     `json:"diagnostic"`
}

type diagnosticMatch struct {
	Expected int          `json:"expected_diagnostics"`
	Observed int          `json:"observed_diagnostics"`
	Matched  int          `json:"matched_diagnostics"`
	Pairs    []pair       `json:"pairs,omitempty"`
	Missing  []annotation `json:"missing_annotations,omitempty"`
	Extra    []diagnostic `json:"extra_diagnostics,omitempty"`
}

func (m diagnosticMatch) complete() bool {
	return m.Expected == m.Observed && m.Matched == m.Expected && len(m.Missing) == 0 && len(m.Extra) == 0
}

// satisfies reports whether d can be consumed by a. A positioned diagnostic
// must sit on the annotation's original line; an autogenerated diagnostic is
// only ever consumed by an ERRORAUTO annotation.
func satisfies(a annotation, d diagnostic) bool {
	if a.Auto != (d.Kind == "autogenerated") {
		return false
	}
	if !a.Auto {
		if d.Original == nil || d.Original.File != a.File || d.Original.Line != a.Line {
			return false
		}
	}
	return a.re.MatchString(d.Text)
}

// matchDiagnosticText and matchDiagnosticRegexp are the policy-neutral exact
// text and whole-text regexp primitives. Annotation matching uses the latter.
func matchDiagnosticText(expected, observed string) bool { return expected == observed }

func matchDiagnosticRegexp(pattern, observed string) (bool, error) {
	re, err := regexp.Compile(`\A(?:` + pattern + `)\z`)
	if err != nil {
		return false, err
	}
	return re.MatchString(observed), nil
}

// matchDiagnostics computes a maximum one-to-one assignment between
// annotations and remapped diagnostics and reports everything left over.
// The result is complete only when the assignment is perfect on both sides.
func matchDiagnostics(want []annotation, got []diagnostic) diagnosticMatch {
	res := diagnosticMatch{Expected: len(want), Observed: len(got)}
	edges := make([][]int, len(want))
	for i, a := range want {
		for j, d := range got {
			if satisfies(a, d) {
				edges[i] = append(edges[i], j)
			}
		}
	}
	// Augmenting-path bipartite matching; inputs are a handful of lines.
	matchOf := make([]int, len(got)) // diagnostic → annotation
	for j := range matchOf {
		matchOf[j] = -1
	}
	var augment func(i int, seen []bool) bool
	augment = func(i int, seen []bool) bool {
		for _, j := range edges[i] {
			if seen[j] {
				continue
			}
			seen[j] = true
			if matchOf[j] < 0 || augment(matchOf[j], seen) {
				matchOf[j] = i
				return true
			}
		}
		return false
	}
	assigned := make([]int, len(want)) // annotation → diagnostic
	for i := range assigned {
		assigned[i] = -1
	}
	for i := range want {
		augment(i, make([]bool, len(got)))
	}
	for j, i := range matchOf {
		if i >= 0 {
			assigned[i] = j
		}
	}
	for i, a := range want {
		if assigned[i] < 0 {
			res.Missing = append(res.Missing, a)
			continue
		}
		res.Matched++
		res.Pairs = append(res.Pairs, pair{Annotation: a, Diagnostic: got[assigned[i]].Remapped})
	}
	for j, d := range got {
		if matchOf[j] < 0 {
			res.Extra = append(res.Extra, d)
		}
	}
	return res
}

// byteMatch is the outcome of an exact byte comparison.
type byteMatch struct {
	Equal           bool   `json:"equal"`
	ExpectedBytes   int    `json:"expected_bytes"`
	ObservedBytes   int    `json:"observed_bytes"`
	FirstDifference int    `json:"first_difference,omitempty"`
	Kind            string `json:"kind,omitempty"` // missing | extra | differs
}

// matchBytes compares whole byte strings. A truncated observation is
// "missing", a longer one "extra", and a divergence "differs" at the first
// differing offset. No trimming, no newline or encoding normalization.
func matchBytes(expected, observed []byte) byteMatch {
	res := byteMatch{ExpectedBytes: len(expected), ObservedBytes: len(observed)}
	n := min(len(expected), len(observed))
	for i := 0; i < n; i++ {
		if expected[i] != observed[i] {
			res.FirstDifference, res.Kind = i, "differs"
			return res
		}
	}
	switch {
	case len(observed) < len(expected):
		res.FirstDifference, res.Kind = n, "missing"
	case len(observed) > len(expected):
		res.FirstDifference, res.Kind = n, "extra"
	default:
		res.Equal = true
	}
	return res
}
