#!/usr/bin/env python3
"""Archive-authenticated, exhaustive Go corpus inputs and static recipe roots.

This command never executes a tested Go program and cannot certify parity.
"""
import argparse
import collections
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile

REPO = Path(__file__).resolve().parents[2]
SCHEMA = 1
ACTIONS = {
    "asmcheck": ["compile-assembly", "match-assembly"],
    "build": ["build"],
    "builddir": ["assemble-symabis-if-present", "compile", "assemble-if-present", "pack", "link"],
    "buildrun": ["build", "run", "match-output"],
    "buildrundir": ["assemble-symabis-if-present", "compile", "assemble-if-present", "pack", "link", "run", "match-output"],
    "compile": ["compile"],
    "compiledir": ["compile-packages-in-order"],
    "errorcheck": ["compile", "match-diagnostics"],
    "errorcheckandrundir": ["compile-packages-in-order", "match-diagnostics", "compile-packages-in-order", "link", "run", "match-output"],
    "errorcheckdir": ["compile-packages-in-order", "match-diagnostics"],
    "errorcheckoutput": ["run-generator", "capture-generated-source", "compile-generated-source", "match-generated-diagnostics"],
    "errorcheckwithauto": ["compile", "match-diagnostics-including-autogenerated"],
    "run": ["compile-or-build", "link-if-needed", "run", "match-output"],
    "rundir": ["compile-packages-in-order", "link", "run", "match-output"],
    "runindir": ["overlay-directory", "generate-module", "build-and-run-package", "match-output"],
    "runoutput": ["run-generator", "capture-generated-source", "build-and-run-generated-source", "match-output"],
    "skip": ["upstream-explicit-skip"],
}
DIR_ACTIONS = {"compiledir", "errorcheckdir", "errorcheckandrundir", "rundir", "runindir", "builddir", "buildrundir"}
PACKAGE_ACTIONS = {"compiledir", "errorcheckdir", "errorcheckandrundir", "rundir"}
OUTPUT_ACTIONS = {key for key, phases in ACTIONS.items() if "match-output" in phases}
GENERATORS = {"runoutput", "errorcheckoutput"}
SCOPES = ("test/", "src/cmd/compile/", "src/cmd/internal/testdir/", "src/go/types/", "src/internal/types/")


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def rows(path):
    return [line.split("\t") for line in Path(path).read_text().splitlines() if line and not line.startswith("#")]


def pins():
    corpus = rows(REPO / "docs/go-corpus/pin.tsv")
    oracle = rows(REPO / "docs/go-oracle/pin.tsv")
    require(len(corpus) == len(oracle) == 1, "expected exactly one corpus and oracle pin")
    c, o = corpus[0], oracle[0]
    require(len(c) == 9 and len(o) == 10, "malformed reviewed pins")
    require(c[0] == o[0] and c[1] == "source", "release pin mismatch")
    require(c[2] == c[0] + ".src.tar.gz" and c[3] == "https://go.dev/dl/" + c[2], "invalid official archive URL")
    return {"release": c[0], "filename": c[2], "url": c[3], "sha256": c[4], "historical_files": int(c[5]),
            "historical_sha256": c[8], "license": c[6], "semantics_path": o[1], "semantics_sha256": o[2]}


def archive_files(archive, pin):
    require(sha(Path(archive).read_bytes()) == pin["sha256"], "source archive checksum mismatch")
    contents = {}
    with tarfile.open(archive, "r:gz") as tf:
        for member in tf:
            p = PurePosixPath(member.name)
            require(not p.is_absolute() and p.parts[0] == "go" and ".." not in p.parts,
                    "unsafe archive member: " + member.name)
            if member.isdir():
                continue
            require(member.isfile(), "non-regular archive member: " + member.name)
            name = str(PurePosixPath(*p.parts[1:]))
            require(name not in contents, "duplicate archive member: " + name)
            contents[name] = tf.extractfile(member).read()
    require(sha(contents[pin["semantics_path"]]) == pin["semantics_sha256"], "upstream semantics checksum mismatch")
    require("LICENSE" in contents and contents["VERSION"].splitlines()[0].decode() == pin["release"], "source identity mismatch")
    return contents


def verify_source(root, files):
    """Reject added, missing, linked, or changed files anywhere in the source tree."""
    require(root.is_dir() and not root.is_symlink(), "source root must be a regular directory")
    actual = set()
    expected_dirs = {str(parent) for name in files for parent in PurePosixPath(name).parents if str(parent) != "."}
    for base, dirs, names in os.walk(root, followlinks=False):
        for name in dirs + names:
            p = Path(base) / name
            require(not p.is_symlink(), "linked source member: " + str(p))
            if name in dirs:
                require(p.relative_to(root).as_posix() in expected_dirs, "added source directory: " + str(p))
        for name in names:
            p = Path(base) / name
            require(p.is_file(), "non-regular source member: " + str(p))
            rel = p.relative_to(root).as_posix()
            actual.add(rel)
            require(rel in files, "added source file: " + rel)
            require(p.read_bytes() == files[rel], "source bytes changed: " + rel)
    require(actual == set(files), "missing source files: " + repr(sorted(set(files) - actual)[:10]))


def materialize(cache, pin):
    cache.mkdir(parents=True, exist_ok=True)
    archive = cache / pin["filename"]
    if not archive.exists():
        fd, tmp = tempfile.mkstemp(prefix="download-", dir=cache)
        os.close(fd)
        try:
            subprocess.run(["curl", "--fail", "--location", "--silent", "--show-error", pin["url"], "-o", tmp], check=True)
            require(sha(Path(tmp).read_bytes()) == pin["sha256"], "download checksum mismatch")
            os.replace(tmp, archive)
        finally:
            Path(tmp).unlink(missing_ok=True)
    files = archive_files(archive, pin)
    root = cache / "go"
    if root.exists():
        verify_source(root, files)
    else:
        stage = Path(tempfile.mkdtemp(prefix="source-", dir=cache))
        try:
            for name, data in files.items():
                p = stage / name
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_bytes(data)
            # Inventory consumers only read source. Executable tool scripts remain
            # 0644: executions must create a separate working copy if needed.
            os.rename(stage, root)
        finally:
            if stage.exists():
                shutil.rmtree(stage)
    return archive, root, files


def split_quoted(s):
    """Same backslash/quote state machine as pinned testdir splitQuoted."""
    out, arg, quote, quoted, escaped = [], [], None, False, False
    for ch in s:
        if escaped:
            escaped = False
        elif ch == "\\":
            escaped = True
            continue
        elif quote:
            if ch == quote:
                quote = None
                continue
        elif ch in "\"'":
            quote, quoted = ch, True
            continue
        elif ch.isspace():
            if quoted or arg:
                out.append("".join(arg))
                arg, quoted = [], False
            continue
        arg.append(ch)
    require(not quote and not escaped, "malformed quoted recipe: " + s)
    if quoted or arg:
        out.append("".join(arg))
    return out


def recipe_line(data):
    s = data.decode("utf-8", errors="replace")
    require(not s.startswith("\n"), "upstream root starts with newline")
    for line in s.splitlines():
        # Go's constraint.Is{Go,Plus}Build requires a token boundary.
        if re.match(r"^//go:build(?:\s|$)", line) or re.match(r"^//\s*\+build(?:\s|$)", line):
            continue
        line = line.removeprefix("//").strip()
        if line:
            return line
    raise ValueError("missing upstream recipe")


def parse_recipe(data):
    line = recipe_line(data)
    tokens = split_quoted(line)
    require(tokens and tokens[0] in ACTIONS, "unknown upstream action: " + line)
    action, rest = tokens[0], tokens[1:]
    result = {"line": line, "action": action, "flags": [], "args": [], "single_file_packages": False,
              "want_error": action in {"errorcheck", "errorcheckdir", "errorcheckoutput", "errorcheckwithauto"},
              "want_autogenerated_diagnostics": action == "errorcheckwithauto", "environment_append": []}
    while rest and rest[0].startswith("-"):
        flag, rest = rest[0], rest[1:]
        if flag in {"-0", "-1"}:
            result["want_error"] = flag == "-1"
        elif flag == "-s":
            result["single_file_packages"] = True
        elif flag in {"-t", "-goexperiment", "-godebug", "-gomodversion"}:
            require(rest, "missing value for " + flag)
            value, rest = rest[0], rest[1:]
            if flag == "-t":
                result["timeout_seconds_before_scale"] = int(value)
            elif flag == "-gomodversion":
                result["module_go_version"] = value
            else:
                result["environment_append"].append([{"-godebug": "GODEBUG", "-goexperiment": "GOEXPERIMENT"}[flag], value])
        else:
            result["flags"].append(flag)
    result["args"] = rest
    result["effective_action"] = "errorcheck" if action == "errorcheckwithauto" else action
    result["effective_flags"] = list(result["flags"])
    if result["effective_action"] == "errorcheck":
        for i, flag in enumerate(result["effective_flags"]):
            if flag.startswith("-d="):
                result["effective_flags"][i] += ",ssa/check/on"
                break
        else:
            result["effective_flags"].append("-d=ssa/check/on")
    return result


def constraints(data):
    # Preserve header directives, without deciding applicability for an unbound
    # GOOS/GOARCH/experiments/compiler/options tuple.
    header = data.decode("utf-8", errors="replace").split("\npackage", 1)[0]
    return [line for line in header.splitlines() if re.match(r"^//(?:go:build|\s*\+build)(?:\s|$)", line)]


def fingerprint(name, files):
    data = files[name]
    return {"path": name, "bytes": len(data), "sha256": sha(data)}


def package_groups(names, files, single):
    groups, by_name = [], {}
    for name in names:
        match = re.search(r"(?m)^package ([\w]+)", files[name].decode("utf-8", errors="replace"))
        require(match, "cannot find package name: " + name)
        package = match[1]
        if single or package not in by_name:
            group = {"ordinal": len(groups), "package": package, "files": []}
            groups.append(group)
            by_name[package] = group
        by_name[package]["files"].append(name)
    return groups


def history(files, pin):
    invpath = REPO / "docs/go-corpus/inventory.tsv"
    raw = b"".join(line + b"\n" for line in invpath.read_bytes().splitlines() if line and not line.startswith(b"#"))
    require(sha(raw) == pin["historical_sha256"], "historical inventory checksum mismatch")
    old = rows(invpath)
    expected = sorted(p for p in files if p.startswith("test/") and p.endswith(".go"))
    require(len(old) == pin["historical_files"] and [r[0] for r in old] == expected, "historical source denominator mismatch")
    for p, action, size, digest in old:
        require(len(files[p]) == int(size) and sha(files[p]) == digest, "historical source digest mismatch: " + p)
    return old


def historical_roots(files, pin):
    source = files[pin["semantics_path"]].decode()
    match = re.search(r"\bdirs = \[\]string\{([^}]+)\}", source)
    require(match, "missing runner dirs")
    dirs = re.findall(r'"([^"]+)"', match[1])
    switch = source.split("\tswitch action {\n", 1)[1].split("\n\tdefault:", 1)[0]
    actions = set()
    for line in switch.splitlines():
        if line.startswith("\tcase "):
            actions.update(re.findall(r'"([a-z]+)"', line))
    require(actions == set(ACTIONS), "upstream action vocabulary drift")
    failures = {}
    for key in ("types2Failures", "types2Failures32Bit"):
        match = re.search(r"var " + key + r" = setOf\((.*?)\n\)", source, re.S)
        require(match, "missing expected failure set " + key)
        failures[key] = re.findall(r'^\s*"([^"]+)"', match[1], re.M)
    parents = {"test" if d == "." else "test/" + d for d in dirs}
    roots, owners = [], collections.defaultdict(list)
    for p in sorted(files):
        path = PurePosixPath(p)
        if str(path.parent) not in parents or not p.endswith(".go") or path.name.startswith("."):
            continue
        try:
            recipe = parse_recipe(files[p])
        except ValueError:
            # The runner evaluates build constraints before validating action.
            # linkmain.go is enumerated, then ignored, and serves linkmain_run.go.
            require(p == "test/linkmain.go" and constraints(files[p]) == ["//go:build ignore"],
                    "unclassified invalid root recipe: " + p)
            recipe = {"line": recipe_line(files[p]), "action": None,
                      "validity": "invalid-if-forced-past-build-ignore"}
        action = recipe["action"]
        root = {"id": "testdir:" + p.removeprefix("test/"), "path": p, "upstream_subtest": "Test/" + p.removeprefix("test/"),
                "recipe": recipe, "build_constraints": constraints(files[p]), "input_files": [p],
                "expected_failure_sets": [k for k, names in failures.items() if p.removeprefix("test/") in names],
                "execution_status": "not-executed", "applicability": "requires-bound-execution-environment"}
        if action in DIR_ACTIONS:
            directory = p[:-3] + ".dir"
            names = sorted(n for n in files if n.startswith(directory + "/"))
            require(names, "missing or empty recipe directory: " + directory)
            root["directory"] = {"path": directory, "members": names,
                                 "manifest_sha256": sha("".join(n[len(directory)+1:] + "\t" + sha(files[n]) + "\n" for n in names).encode())}
            root["input_files"] += names
            direct_go = [n for n in names if str(PurePosixPath(n).parent) == directory and n.endswith(".go")]
            if action in PACKAGE_ACTIONS:
                root["package_groups"] = package_groups(direct_go, files, recipe["single_file_packages"])
                require(root["package_groups"], "no package inputs: " + directory)
                root["direct_compile_inputs"] = direct_go
            elif action in {"builddir", "buildrundir"}:
                root["direct_compile_inputs"] = direct_go
                root["direct_assembly_inputs"] = [n for n in names if str(PurePosixPath(n).parent) == directory and n.endswith(".s")]
            else:
                root["module_path"] = PurePosixPath(directory).name
                root["module_go_version"] = recipe.get("module_go_version", "1.14")
        # Several //run programs invoke the Go tool themselves. Preserve their
        # associated directory even though testdir does not compile it directly.
        program_dir = p[:-3] + ".dir"
        program_members = sorted(n for n in files if n.startswith(program_dir + "/"))
        if program_members and action not in DIR_ACTIONS:
            root["program_directory_inputs"] = program_members
            root["input_files"] += program_members
        text = files[p].decode("utf-8", errors="replace")
        if '"os/exec"' in text:
            root["nested_process_obligation"] = {
                "detection": "os/exec import string; candidate requiring runtime process observation",
                "generated_program_denominator": None,
                "required_evidence": "capture child argv, environment, exit, source bytes and generated artifacts; bind tested stages to each product mode",
            }
            # Conservative static references. These are candidates, not a claim
            # that every string executes or that runtime dependencies end here.
            candidates = set()
            for literal in re.findall(r'"([^"\n]+\.go)"', text):
                name = os.path.normpath(str(path.parent) + "/" + literal)
                if name in files:
                    candidates.add(name)
            root["source_reference_candidates"] = sorted(candidates)
        if action in OUTPUT_ACTIONS:
            sidecar = p[:-3] + ".out"
            root["expected_output"] = ({"present": True, **fingerprint(sidecar, files)} if sidecar in files else
                                       {"present": False, "path": sidecar, "bytes": 0, "sha256": None})
            if sidecar in files:
                root["input_files"].append(sidecar)
        if action in GENERATORS:
            root["generated_program"] = {"artifact_name": "tmp__.go", "expected_artifacts_per_applicable_recipe": 1,
                                         "content_sha256": None, "state": "requires-generator-execution",
                                         "downstream_phase": "run" if action == "runoutput" else "diagnostic-check"}
        for name in root["input_files"]:
            owners[name].append(root["id"])
        roots.append(root)
    return roots, owners, dirs, failures


def typecheck_roots(files):
    result = []
    for package in ("src/go/types", "src/cmd/compile/internal/types2"):
        runner = package + "/check_test.go"
        text = files[runner].decode()
        calls = re.findall(r'testDirFiles\(t, "([^"]+)"(?:, (\d+))?, false\)', text)
        require(len(calls) == 5, "typecheck recipe families drifted: " + runner)
        families = ("TestCheck", "TestSpec", "TestExamples", "TestFixedbugs", "TestLocal")
        for family, (relative, tolerance) in zip(families, calls):
            directory = os.path.normpath(package + "/" + relative)
            prefix = directory + "/"
            names = sorted(n for n in files if n.startswith(prefix))
            require(names, "missing typechecker family: " + directory)
            children = sorted({n[len(prefix):].split("/", 1)[0] for n in names})
            for child in children:
                p = prefix + child
                members = [n for n in names if n == p or n.startswith(p + "/")]
                # testDir reads direct children only; a nested directory here
                # would be an upstream read error, not a recursive new test.
                require(all(n == p or "/" not in n.removeprefix(p + "/") for n in members), "nested typecheck recipe directory: " + p)
                result.append({"id": package.removeprefix("src/") + ":" + family + "/" + child,
                               "runner": runner, "runner_sha256": sha(files[runner]), "family": family, "path": p,
                               "input_files": members, "column_tolerance": int(tolerance) if tolerance else 0,
                               "build_constraints": {n: constraints(files[n]) for n in members},
                               "execution_status": "not-executed", "applicability": "requires-bound-checker-environment"})
    return result


def package_roots(files):
    # Package roots are a separate denominator: runtime-generated subtests and
    # generated source literals require actual go test -json execution to count.
    tests = collections.defaultdict(list)
    for p in sorted(files):
        if not p.endswith("_test.go") or not p.startswith(SCOPES[1:]):
            continue
        parts = PurePosixPath(p).parts
        if any(x == "testdata" or x == "vendor" or x.startswith((".", "_")) for x in parts[:-1]):
            continue
        tests[str(PurePosixPath(p).parent)].append(p)
    return [{"id": "package:" + package.removeprefix("src/"), "package": package.removeprefix("src/"),
             "test_files": names, "source_files": sorted(p for p in files if str(PurePosixPath(p).parent) == package and p.endswith(".go")),
             "runtime_test_case_denominator": None, "execution_status": "not-executed",
             "applicability": "requires-go-list-with-bound-environment"} for package, names in sorted(tests.items())]


def render(files, pin):
    old = history(files, pin)
    roots, owners, dirs, failures = historical_roots(files, pin)
    types = typecheck_roots(files)
    packages = package_roots(files)
    action_counts = collections.Counter(r["recipe"]["action"] for r in roots if r["recipe"]["action"] is not None)
    root_paths = {r["path"] for r in roots}
    historical = []
    for p, old_action, size, digest in old:
        require(p in root_paths or owners[p] or p.startswith("test/stress/"), "unclassified historical input: " + p)
        historical.append({"path": p, "bytes": int(size), "sha256": digest, "historical_action": old_action,
                           "role": "test-root" if p in root_paths else "directory-input" if owners[p] else "outside-testdir-scope",
                           "scope_reason": None if owners[p] else "test/stress is absent from pinned runner dirs; runtime stress tools require a separately bounded campaign",
                           "root_owners": owners[p]})
    file_rows = []
    for p in sorted(files):
        if p.startswith(SCOPES) or p in {"LICENSE", "VERSION", "go.env"}:
            file_rows.append(fingerprint(p, files))
    summary = {"schema_version": SCHEMA, "evidence_kind": "static-inventory", "execution_claim": False,
               "pin": pin, "runner_directories": dirs, "expected_failure_sets": failures,
               "denominators": {"archive_regular_files": len(files), "scoped_files": len(file_rows),
                   "historical_go_source_files": len(old), "testdir_roots": len(roots), "testdir_actions": dict(sorted(action_counts.items())),
                   "runner_action_vocabulary": len(ACTIONS), "roots_without_valid_action": sum(r["recipe"]["action"] is None for r in roots), "historical_roles": dict(sorted(collections.Counter(r["role"] for r in historical).items())),
                   "historical_action_none": sum(r[1] == "none" for r in old),
                   "directory_recipe_roots": sum("directory" in r for r in roots),
                   "directory_member_references": sum(len(r.get("directory", {}).get("members", [])) for r in roots),
                   "directory_package_groups": sum(len(r.get("package_groups", [])) for r in roots),
                   "sidecar_expectations": sum("expected_output" in r for r in roots),
                   "sidecars_present": sum(r.get("expected_output", {}).get("present", False) for r in roots),
                   "generator_recipe_roots": sum("generated_program" in r for r in roots),
                   "nested_process_candidate_roots": sum("nested_process_obligation" in r for r in roots),
                   "program_directory_input_references": sum(len(r.get("program_directory_inputs", [])) for r in roots),
                   "generated_programs_observed": 0, "runtime_generated_test_cases": None, "nested_generated_program_denominator": None,
                   "test_package_roots": len(packages), "typechecker_static_roots": len(types),
                   "typechecker_distinct_input_files": len({n for r in types for n in r["input_files"]}),
                   "executed_roots": 0},
               "coverage_note": "Roots, packages, source inputs and generated obligations overlap; do not add them into a single test count. No platform or unsupported-product exclusions were applied."}
    catalog = [{"action": action, "root_count": action_counts[action], "phase_contract": phases,
                "directory_recipe": action in DIR_ACTIONS, "consumes_expected_output": action in OUTPUT_ACTIONS,
                "generates_tested_program": action in GENERATORS, "implemented_executor": False,
                "semantics_path": pin["semantics_path"], "semantics_sha256": pin["semantics_sha256"]} for action, phases in sorted(ACTIONS.items())]
    artifacts = {"summary.json": pretty(summary), "action-catalog.json": pretty(catalog)}
    for name, values in (("files", file_rows), ("historical-sources", historical), ("testdir-roots", roots), ("typechecker-roots", types), ("package-roots", packages)):
        artifacts[name + ".jsonl"] = "".join(json.dumps(r, sort_keys=True, separators=(",", ":")) + "\n" for r in values).encode()
    return artifacts, summary


def pretty(value):
    return (json.dumps(value, sort_keys=True, indent=2) + "\n").encode()


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("command", choices=["materialize", "generate", "validate"])
    p.add_argument("--cache", type=Path, default=REPO / ".cache/go-full")
    p.add_argument("--archive", type=Path)
    p.add_argument("--source-root", type=Path)
    p.add_argument("--output", type=Path, default=REPO / "docs/go-full")
    a = p.parse_args()
    pin = pins()
    if a.command == "materialize":
        archive, root, files = materialize(a.cache, pin)
        print(json.dumps({"archive": str(archive.resolve()), "source_root": str(root.resolve()), "archive_sha256": pin["sha256"], "verified_files": len(files)}))
        return
    archive, root = a.archive or a.cache / pin["filename"], a.source_root or a.cache / "go"
    files = archive_files(archive, pin)
    verify_source(root, files)
    artifacts, summary = render(files, pin)
    if a.command == "generate":
        a.output.mkdir(parents=True, exist_ok=True)
        for name, data in artifacts.items():
            (a.output / name).write_bytes(data)
    else:
        for name, data in artifacts.items():
            require((a.output / name).read_bytes() == data, "inventory drift or tampering: " + name)
    print(json.dumps({"status": "inventory-verified", "execution_claim": False, "source_root": str(root.resolve()), "denominators": summary["denominators"]}, sort_keys=True))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, KeyError, IndexError, tarfile.TarError, subprocess.CalledProcessError) as exc:
        print("FATAL: " + str(exc), file=sys.stderr)
        sys.exit(2)
