#!/usr/bin/env python3
"""Negative provenance tests and concrete upstream recipe boundary checks."""
import importlib.util
import io
import json
from pathlib import Path
import tarfile
import tempfile
import unittest
import sys
sys.dont_write_bytecode = True

REPO = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("go_full_inventory", REPO / "tools/go-full/inventory.py")
inv = importlib.util.module_from_spec(spec)
spec.loader.exec_module(inv)


class ProvenanceTests(unittest.TestCase):
    def test_file_mutation_addition_and_deletion(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "source.go"
            data = b'package main\nfunc main() {}\n'
            files = {"source.go": data}
            source.write_bytes(data)
            inv.verify_source(root, files)
            extra_dir = root / "unexpected-fixture"
            extra_dir.mkdir()
            with self.assertRaisesRegex(ValueError, "added source directory"):
                inv.verify_source(root, files)
            extra_dir.rmdir()
            source.write_bytes(data + b"// tampered\n")
            with self.assertRaisesRegex(ValueError, "source bytes changed"):
                inv.verify_source(root, files)
            source.write_bytes(data)
            added = root / "source.out"
            added.write_bytes(b"forged expectation")
            with self.assertRaisesRegex(ValueError, "added source file"):
                inv.verify_source(root, files)
            added.unlink()
            source.unlink()
            with self.assertRaisesRegex(ValueError, "missing source files"):
                inv.verify_source(root, files)

    def test_symlink_even_with_identical_bytes_is_rejected(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "original").write_bytes(b"same")
            (root / "linked").symlink_to("original")
            with self.assertRaisesRegex(ValueError, "linked source member"):
                inv.verify_source(root, {"original": b"same", "linked": b"same"})

    def test_archive_checksum_precedes_extraction(self):
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp) / "fake.tar.gz"
            archive.write_bytes(b"not an archive")
            with self.assertRaisesRegex(ValueError, "source archive checksum mismatch"):
                inv.archive_files(archive, {"sha256": "0" * 64})

    def test_archive_path_and_duplicate_members_fail_closed(self):
        for names, message in ((["go/../outside"], "unsafe archive member"), (["go/file", "go/file"], "duplicate archive member")):
            with self.subTest(names=names), tempfile.TemporaryDirectory() as tmp:
                archive = Path(tmp) / "fake.tar.gz"
                with tarfile.open(archive, "w:gz") as tf:
                    for name in names:
                        entry = tarfile.TarInfo(name)
                        entry.size = 1
                        tf.addfile(entry, io.BytesIO(b"x"))
                with self.assertRaisesRegex(ValueError, message):
                    inv.archive_files(archive, {"sha256": inv.sha(archive.read_bytes())})

    def test_recipe_unknown_or_unterminated_is_fatal(self):
        for data in (b"// madeup\npackage main", b'// run "unterminated\npackage main', b"// run -t\npackage main"):
            with self.subTest(data=data), self.assertRaises(ValueError):
                inv.parse_recipe(data)

    def test_upstream_recipe_quote_environment_and_rejection_semantics(self):
        # splitQuoted treats a backslash as an escape even inside single quotes,
        # unlike POSIX shlex: replacing it with a shell parser changes recipes.
        self.assertEqual(inv.split_quoted(r'''a b:"c d" 'e''f' "g\"" 'h\i' '''), ["a", "b:c d", "ef", 'g"', "hi"])
        recipe = inv.parse_recipe(b"//go:build amd64\n\n// errorcheckwithauto -0 -s -d=checkptr -goexperiment a -goexperiment b\npackage p")
        self.assertEqual(recipe["action"], "errorcheckwithauto")
        self.assertEqual(recipe["effective_action"], "errorcheck")
        self.assertFalse(recipe["want_error"])
        self.assertTrue(recipe["want_autogenerated_diagnostics"])
        self.assertEqual(recipe["environment_append"], [["GOEXPERIMENT", "a"], ["GOEXPERIMENT", "b"]])
        self.assertEqual(recipe["effective_flags"], ["-d=checkptr,ssa/check/on"])


class PinnedInventoryTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.roots = {r["path"]: r for r in map(json.loads, (REPO / "docs/go-full/testdir-roots.jsonl").read_text().splitlines())}
        cls.sources = {r["path"]: r for r in map(json.loads, (REPO / "docs/go-full/historical-sources.jsonl").read_text().splitlines())}

    def test_build_ignore_root_is_retained_before_action_validation(self):
        root = self.roots["test/linkmain.go"]
        self.assertIsNone(root["recipe"]["action"])
        self.assertEqual(root["build_constraints"], ["//go:build ignore"])
        self.assertEqual(root["execution_status"], "not-executed")

    def test_run_driver_directory_inputs_are_not_lost(self):
        for path in ("test/fixedbugs/bug369.dir/main.go", "test/fixedbugs/bug369.dir/pkg.go", "test/fixedbugs/issue9355.dir/a.go"):
            row = self.sources[path]
            self.assertEqual(row["role"], "directory-input")
            self.assertEqual(len(row["root_owners"]), 1)
        self.assertEqual(self.sources["test/stress/runstress.go"]["role"], "outside-testdir-scope")

    def test_no_source_file_is_misrepresented_as_executed(self):
        self.assertEqual(len(self.sources), 3398)
        self.assertEqual(len(self.roots), 2726)
        self.assertEqual({r["execution_status"] for r in self.roots.values()}, {"not-executed"})
        generators = [r for r in self.roots.values() if "generated_program" in r]
        self.assertEqual(len(generators), 26)
        self.assertTrue(all(r["generated_program"]["content_sha256"] is None for r in generators))
        self.assertIn("nested_process_obligation", self.roots["test/nosplit.go"])
        self.assertIsNone(self.roots["test/nosplit.go"]["nested_process_obligation"]["generated_program_denominator"])

    def test_absent_sidecar_is_a_binding_expectation(self):
        root = self.roots["test/helloworld.go"]
        self.assertEqual(root["expected_output"]["path"], "test/helloworld.out")
        absent = next(r["expected_output"] for r in self.roots.values() if "expected_output" in r and not r["expected_output"]["present"])
        self.assertIsNone(absent["sha256"])
        self.assertEqual(absent["bytes"], 0)


if __name__ == "__main__":
    unittest.main()
