package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

var (
	errRx       = regexp.MustCompile(`// (?:GC_)?ERROR (.*)`)
	errAutoRx   = regexp.MustCompile(`// (?:GC_)?ERRORAUTO (.*)`)
	errQuotesRx = regexp.MustCompile(`"([^"]*)"`)
	lineRx      = regexp.MustCompile(`LINE(([+-])(\d+))?`)
)

type wantedError struct {
	reStr   string
	re      *regexp.Regexp
	lineNum int
	auto    bool
	file    string
	prefix  string
}

// splitOutput splits compiler output at the start of each line that does not
// begin with a tab, so a multi-line diagnostic stays one message.
func splitOutput(out string, wantAuto bool) []string {
	var res []string
	for _, line := range strings.Split(out, "\n") {
		if strings.HasSuffix(line, "\r") {
			line = line[:len(line)-1]
		}
		if strings.HasPrefix(line, "\t") {
			if len(res) == 0 {
				continue
			}
			res[len(res)-1] += "\n" + line
		} else if strings.HasPrefix(line, "go tool") || strings.HasPrefix(line, "#") ||
			(!wantAuto && strings.HasPrefix(line, "<autogenerated>")) {
			continue
		} else if strings.TrimSpace(line) != "" {
			res = append(res, line)
		}
	}
	return res
}

func replacePrefix(s, old, new string) string {
	if !strings.Contains(s, old) {
		return s
	}
	s = strings.ReplaceAll(s, " "+old, " "+new)
	s = strings.ReplaceAll(s, "\n"+old, "\n"+new)
	s = strings.ReplaceAll(s, "\n\t"+old, "\n\t"+new)
	if strings.HasPrefix(s, old) {
		s = new + s[len(old):]
	}
	return s
}

// matchPrefix reports whether s is of the form ^(.*/)?prefix(:|[).
func matchPrefix(s, prefix string) bool {
	s = s[len(filepath.VolumeName(s)):]
	i := strings.Index(s, ":")
	if i < 0 {
		return false
	}
	j := strings.LastIndex(s[:i], string(filepath.Separator))
	s = s[j+1:]
	if len(s) <= len(prefix) || s[:len(prefix)] != prefix {
		return false
	}
	switch s[len(prefix)] {
	case '[', ':':
		return true
	}
	return false
}

func partitionStrings(prefix string, strs []string) (matched, unmatched []string) {
	for _, s := range strs {
		if matchPrefix(s, prefix) {
			matched = append(matched, s)
		} else {
			unmatched = append(unmatched, s)
		}
	}
	return
}

// wantedErrors reads the `// ERROR "regexp"` annotations out of a source file.
func wantedErrors(file, short string) ([]wantedError, error) {
	cache := make(map[string]*regexp.Regexp)
	src, err := os.ReadFile(file)
	if err != nil {
		return nil, err
	}
	var errs []wantedError
	for i, line := range strings.Split(string(src), "\n") {
		lineNum := i + 1
		if strings.Contains(line, "////") {
			// A double comment disables the annotation.
			continue
		}
		var auto bool
		m := errAutoRx.FindStringSubmatch(line)
		if m != nil {
			auto = true
		} else {
			m = errRx.FindStringSubmatch(line)
		}
		if m == nil {
			continue
		}
		mm := errQuotesRx.FindAllStringSubmatch(m[1], -1)
		if mm == nil {
			return nil, fmt.Errorf("%s:%d: invalid errchk line: %s", short, lineNum, line)
		}
		for _, q := range mm {
			rx := lineRx.ReplaceAllStringFunc(q[1], func(s string) string {
				n := lineNum
				if strings.HasPrefix(s, "LINE+") {
					delta, _ := strconv.Atoi(s[5:])
					n += delta
				} else if strings.HasPrefix(s, "LINE-") {
					delta, _ := strconv.Atoi(s[5:])
					n -= delta
				}
				return fmt.Sprintf("%s:%d", short, n)
			})
			re := cache[rx]
			if re == nil {
				re, err = regexp.Compile(rx)
				if err != nil {
					return nil, fmt.Errorf("%s:%d: invalid regexp %q in ERROR line: %v", short, lineNum, rx, err)
				}
				cache[rx] = re
			}
			errs = append(errs, wantedError{
				reStr:   rx,
				re:      re,
				prefix:  fmt.Sprintf("%s:%d", short, lineNum),
				auto:    auto,
				lineNum: lineNum,
				file:    short,
			})
		}
	}
	return errs, nil
}

// errorCheck matches compiler diagnostics against the `// ERROR` annotations in
// the sources. An unannotated diagnostic fails just as loudly as a missing one:
// that symmetry is what stops an errorcheck fixture from passing by accident.
func errorCheck(outStr string, wantAuto bool, fullshort ...string) error {
	var errs []error
	out := splitOutput(outStr, wantAuto)

	for i := range out {
		for j := 0; j+1 < len(fullshort); j += 2 {
			out[i] = replacePrefix(out[i], fullshort[j], fullshort[j+1])
		}
	}

	var want []wantedError
	for j := 0; j+1 < len(fullshort); j += 2 {
		w, err := wantedErrors(fullshort[j], fullshort[j+1])
		if err != nil {
			return err
		}
		want = append(want, w...)
	}

	for _, we := range want {
		var errmsgs []string
		if we.auto {
			errmsgs, out = partitionStrings("<autogenerated>", out)
		} else {
			errmsgs, out = partitionStrings(we.prefix, out)
		}
		if len(errmsgs) == 0 {
			errs = append(errs, fmt.Errorf("%s:%d: missing error %q", we.file, we.lineNum, we.reStr))
			continue
		}
		matched := false
		n := len(out)
		for _, errmsg := range errmsgs {
			text := errmsg
			if _, suffix, ok := strings.Cut(text, " "); ok {
				text = suffix
			}
			if we.re.MatchString(text) {
				matched = true
			} else {
				out = append(out, errmsg)
			}
		}
		if !matched {
			errs = append(errs, fmt.Errorf("%s:%d: no match for %#q in:\n\t%s",
				we.file, we.lineNum, we.reStr, strings.Join(out[n:], "\n\t")))
		}
	}

	if len(out) > 0 {
		// A test using -m that instantiates an imported generic function reports
		// errors located in the other package; keep only local ones.
		localOut := make([]string, 0, len(out))
	outLoop:
		for _, errLine := range out {
			for j := 0; j+1 < len(fullshort); j += 2 {
				full, short := fullshort[j], fullshort[j+1]
				if strings.HasPrefix(errLine, full+":") || strings.HasPrefix(errLine, short+":") {
					localOut = append(localOut, errLine)
					continue outLoop
				}
			}
		}
		out = localOut
	}

	if len(out) > 0 {
		errs = append(errs, errors.New("Unmatched Errors:"))
		for _, errLine := range out {
			errs = append(errs, errors.New(errLine))
		}
	}

	switch len(errs) {
	case 0:
		return nil
	case 1:
		return errs[0]
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "\n")
	for _, err := range errs {
		fmt.Fprintf(&buf, "%s\n", err.Error())
	}
	return errors.New(buf.String())
}
