package main

import (
	"fmt"
	"go/build"
	"go/build/constraint"
	"path"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

// upstreamDirs is the GOROOT/test directory list from the upstream runner's
// `dirs` variable. Anything outside it is not a test case — most importantly a
// "<name>.dir" subdirectory, whose files are inputs to a compiledir/rundir test
// and must never be selected as tests in their own right.
var upstreamDirs = []string{
	".", "ken", "chan", "interface", "internal/runtime/sys", "syntax", "dwarf",
	"fixedbugs", "codegen", "abi", "typeparam", "typeparam/mdempsky", "arenas", "simd",
}

func isUpstreamTestDir(dir string) bool {
	return slices.Contains(upstreamDirs, dir)
}

// types2Failures is the upstream known-failure set: these files are expected to
// fail, so a pass is the anomaly. Carried over verbatim so the oracle agrees
// with upstream about which red is the correct red.
var types2Failures = map[string]bool{
	"shift1.go":               true,
	"fixedbugs/issue10700.go": true,
	"fixedbugs/issue18331.go": true,
	"fixedbugs/issue18419.go": true,
	"fixedbugs/issue20233.go": true,
	"fixedbugs/issue20245.go": true,
	"fixedbugs/issue31053.go": true,
}

func expectFail(dir, goFile string) bool {
	return types2Failures[path.Join(dir, goFile)]
}

// THE BOUNDED SEVEN-ACTION TRANCHE.
//
// upstreamActions is the complete action vocabulary of the pinned upstream
// runner's switch. It is asserted against the pinned source at startup (see
// checkActionCoverage), so this list cannot quietly fall behind.
var upstreamActions = []string{
	"asmcheck", "build", "builddir", "buildrun", "buildrundir", "compile",
	"compiledir", "errorcheck", "errorcheckandrundir", "errorcheckdir",
	"errorcheckoutput", "errorcheckwithauto", "run", "rundir", "runindir",
	"runoutput", "skip",
}

// unsupportedActions enumerates, with the reason, every upstream action this
// slice does NOT implement. It is published in the run summary and in
// docs/go-oracle/README.md so that "the oracle is green" can never be read as
// "the oracle is upstream's runner". This driver executes SEVEN of upstream's
// seventeen actions; it is a bounded tranche, not test/run.go.
var unsupportedActions = map[string]string{
	"asmcheck":            "matches generated assembly against // amd64:\"...\" patterns; needs the codegen matcher and -all_codegen cross-GOARCH handling, none of which is implemented here",
	"builddir":            "builds a directory mixing .go and .s inputs; assembler inputs are outside this tranche",
	"buildrun":            "builds with special go command flags and then runs the binary; not implemented here",
	"buildrundir":         "builds a directory and runs the result; not implemented here",
	"errorcheckandrundir": "error-checks a directory and then runs it; the directory error-check matcher is not implemented here",
	"errorcheckdir":       "error-checks every package of a directory; the directory error-check matcher is not implemented here",
	"errorcheckoutput":    "runs the file and error-checks the program it generates; not implemented here",
	"errorcheckwithauto":  "error-check that also matches <autogenerated> diagnostics; the wantAuto path is unexercised by this tranche and is therefore not claimed",
	"runindir":            "runs the test inside a generated module directory (-gomodversion); module scaffolding is not implemented here",
	"skip":                "upstream's explicit skip marker; a skipped file measures nothing, so it has no place in an execution tranche",
}

// checkActionCoverage asserts that the seven supported actions plus the ten
// enumerated unsupported ones are exactly upstream's vocabulary, and that the
// vocabulary list still matches the pinned runner source. Drift in either
// direction is fatal: a new upstream action that nobody classified would
// otherwise be silently absent from the "unsupported" list, which is how a
// bounded tranche starts implying a full run.
func checkActionCoverage(semanticsSrc []byte) error {
	claimed := map[string]bool{}
	for _, a := range trancheActions {
		if reason, dup := unsupportedActions[a]; dup {
			return fmt.Errorf("action %q is both supported and listed unsupported (%s)", a, reason)
		}
		claimed[a] = true
	}
	for a := range unsupportedActions {
		claimed[a] = true
	}
	upstream := map[string]bool{}
	for _, a := range upstreamActions {
		upstream[a] = true
	}
	var missing, extra []string
	for a := range upstream {
		if !claimed[a] {
			missing = append(missing, a)
		}
	}
	for a := range claimed {
		if !upstream[a] {
			extra = append(extra, a)
		}
	}
	sort.Strings(missing)
	sort.Strings(extra)
	if len(missing) > 0 || len(extra) > 0 {
		return fmt.Errorf("action coverage drift: unclassified upstream actions %v, actions claimed but not upstream's %v", missing, extra)
	}

	found, err := actionsInSwitch(semanticsSrc)
	if err != nil {
		return err
	}
	if !slices.Equal(found, slices.Sorted(slices.Values(upstreamActions))) {
		return fmt.Errorf("the pinned upstream runner's action switch is %v, but this driver enumerates %v",
			found, slices.Sorted(slices.Values(upstreamActions)))
	}
	return nil
}

var caseStringRE = regexp.MustCompile(`"([a-z]+)"`)

// actionsInSwitch extracts the case labels of the upstream runner's
// `switch action {` so the enumeration above is derived from the pinned source
// rather than transcribed from it.
func actionsInSwitch(src []byte) ([]string, error) {
	s := string(src)
	i := strings.Index(s, "\tswitch action {\n")
	if i < 0 {
		return nil, fmt.Errorf("cannot find `switch action {` in the pinned upstream runner")
	}
	rest := s[i:]
	j := strings.Index(rest, "\n\tdefault:")
	if j < 0 {
		return nil, fmt.Errorf("cannot find the end of the upstream action switch")
	}
	seen := map[string]bool{}
	var out []string
	for _, line := range strings.Split(rest[:j], "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "case ") {
			continue
		}
		for _, m := range caseStringRE.FindAllStringSubmatch(trimmed, -1) {
			if !seen[m[1]] {
				seen[m[1]] = true
				out = append(out, m[1])
			}
		}
	}
	sort.Strings(out)
	return out, nil
}

// recipe is the parsed action comment of a corpus file.
type recipe struct {
	line           string
	action         string
	args           []string
	flags          []string
	runenv         []string
	wantError      bool
	wantAuto       bool
	singlefilepkgs bool
	timeout        int
	gomodversion   string

	// goexp and godebug are the values the child processes will see. Upstream
	// seeds them from `go env` and APPENDS each -goexperiment/-godebug flag,
	// comma-separated; the "run" fast path is only taken when neither moved.
	goexp   string
	godebug string
}

// parseRecipeLine finds the execution recipe: the first non-empty line that is
// not a build constraint, with its leading "//" removed. Same rule as upstream.
func parseRecipeLine(src string) string {
	var action string
	for rest := src; action == "" && rest != ""; {
		var line string
		line, rest, _ = strings.Cut(rest, "\n")
		if constraint.IsGoBuild(line) || constraint.IsPlusBuild(line) {
			continue
		}
		action = strings.TrimSpace(strings.TrimPrefix(line, "//"))
	}
	return action
}

// parseRecipe mirrors the upstream action/flag switch for the tranche-1 action
// set. Actions outside that set are rejected loudly, and an action upstream
// supports but this slice does not is rejected with the reason, so the boundary
// of the tranche is stated rather than implied: silently degrading an unhandled
// action to "ran nothing" is the exact failure this driver exists to prevent.
//
// env carries the pinned toolchain's own `go env` answers. GOEXPERIMENT and
// GODEBUG seed the child environment the way upstream seeds them, and the
// -goexperiment/-godebug flags APPEND to that seed rather than replacing it.
func parseRecipe(line string, env *goEnv) (*recipe, error) {
	if line == "" {
		return nil, fmt.Errorf("execution recipe not found")
	}
	f, err := splitQuoted(line)
	if err != nil {
		return nil, fmt.Errorf("invalid test recipe: %v", err)
	}
	r := &recipe{line: line, goexp: env.GOEXPERIMENT, godebug: env.GODEBUG}
	if len(f) > 0 {
		r.action = f[0]
		r.args = f[1:]
	}
	switch r.action {
	case "compile", "compiledir", "build", "run", "runoutput", "rundir":
		// nothing to do
	case "errorcheck":
		r.wantError = true
	default:
		if reason, known := unsupportedActions[r.action]; known {
			return nil, fmt.Errorf("action %q is an upstream action this bounded tranche does not implement: %s\n"+
				"  Supported here, and only here: %s.\n"+
				"  This driver is a seven-action tranche, not upstream's full runner.",
				r.action, reason, strings.Join(trancheActions, ", "))
		}
		return nil, fmt.Errorf("action %q is not an action of the pinned upstream runner", r.action)
	}

	args := r.args
	for len(args) > 0 && strings.HasPrefix(args[0], "-") {
		switch args[0] {
		case "-1":
			r.wantError = true
		case "-0":
			r.wantError = false
		case "-s":
			r.singlefilepkgs = true
		case "-t":
			args = args[1:]
			if len(args) == 0 {
				return nil, fmt.Errorf("need number of seconds for -t timeout")
			}
			r.timeout, err = strconv.Atoi(args[0])
			if err != nil {
				return nil, fmt.Errorf("need number of seconds for -t timeout, got %s instead", args[0])
			}
			// Upstream multiplies the declared timeout by $GO_TEST_TIMEOUT_SCALE,
			// which is how slow builders keep the same corpus green. The scale is
			// parsed once, fatally, in resolveTimeoutScale.
			r.timeout *= env.TimeoutScale
		case "-goexperiment":
			args = args[1:]
			if len(args) == 0 {
				return nil, fmt.Errorf("need a value for -goexperiment")
			}
			if r.goexp != "" {
				r.goexp += ","
			}
			r.goexp += args[0]
			r.runenv = append(r.runenv, "GOEXPERIMENT="+r.goexp)
		case "-godebug":
			args = args[1:]
			if len(args) == 0 {
				return nil, fmt.Errorf("need a value for -godebug")
			}
			if r.godebug != "" {
				r.godebug += ","
			}
			r.godebug += args[0]
			r.runenv = append(r.runenv, "GODEBUG="+r.godebug)
		case "-gomodversion":
			args = args[1:]
			if len(args) == 0 {
				return nil, fmt.Errorf("need a value for -gomodversion")
			}
			r.gomodversion = args[0]
		default:
			r.flags = append(r.flags, args[0])
		}
		args = args[1:]
	}
	r.args = args

	if r.action == "errorcheck" {
		found := false
		for i, fl := range r.flags {
			if strings.HasPrefix(fl, "-d=") {
				r.flags[i] = fl + ",ssa/check/on"
				found = true
				break
			}
		}
		if !found {
			r.flags = append(r.flags, "-d=ssa/check/on")
		}
	}
	return r, nil
}

// buildContext answers build-constraint tag queries the way upstream's context
// does. The GOOS/GOARCH here are the PINNED TOOLCHAIN's, read from `go env
// -json` exactly as upstream reads them — not the driver binary's own
// runtime.GOOS/GOARCH, which is a different question and only coincidentally
// the same answer.
type buildContext struct {
	goos       string
	goarch     string
	cgoEnabled bool
	noOptEnv   bool
}

func (c *buildContext) match(name string) bool {
	if name == "" {
		return false
	}
	for _, r := range name {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' && r != '.' {
			return false
		}
	}
	if slices.Contains(build.Default.ReleaseTags, name) {
		return true
	}
	if strings.HasPrefix(name, "goexperiment.") {
		return slices.Contains(build.Default.ToolTags, name)
	}
	if name == "cgo" && c.cgoEnabled {
		return true
	}
	if name == c.goos || name == "gc" {
		return true
	}
	if name == c.goarch {
		return true
	}
	if c.noOptEnv && name == "gcflags_noopt" {
		return true
	}
	if name == "test_run" {
		return true
	}
	return false
}

// shouldTest evaluates build constraints in the file header. A false answer is
// reported as a skip with the offending line, never as a pass.
func shouldTest(header string, ctxt *buildContext) (bool, string) {
	for _, line := range strings.Split(header, "\n") {
		if strings.HasPrefix(line, "package ") {
			break
		}
		if expr, err := constraint.Parse(line); err == nil {
			if !expr.Eval(ctxt.match) {
				return false, line
			}
		}
	}
	return true, ""
}

// splitQuoted splits a recipe line on spaces, honouring single and double
// quotes. Copied in behaviour from go/build.splitQuoted, which the upstream
// runner uses to tokenise the action comment.
func splitQuoted(s string) ([]string, error) {
	var args []string
	arg := make([]rune, len(s))
	escaped := false
	quoted := false
	quote := '\x00'
	i := 0
	for _, r := range s {
		switch {
		case escaped:
			escaped = false
		case r == '\\':
			escaped = true
			continue
		case quote != '\x00':
			if r == quote {
				quote = '\x00'
				continue
			}
		case r == '"' || r == '\'':
			quoted = true
			quote = r
			continue
		case unicode.IsSpace(r):
			if quoted || i > 0 {
				quoted = false
				args = append(args, string(arg[:i]))
				i = 0
			}
			continue
		}
		arg[i] = r
		i++
	}
	if quoted || i > 0 {
		args = append(args, string(arg[:i]))
	}
	if quote != '\x00' {
		return nil, fmt.Errorf("unclosed quote")
	}
	if escaped {
		return nil, fmt.Errorf("unfinished escaping")
	}
	return args, nil
}
