#!/usr/bin/env bash
# Classify every candidate Bash++ start-site shape against real GNU Bash 5.3.
#
# The committed start-site table that the Bash++ design of record needs is not
# prose to be authored — it is DERIVABLE, and this derives it.
#
#   Class R  stock bash 5.3 REJECTS the shape.  Purely additive: no existing
#            script can contain it, so Bash++ may claim it with no table row,
#            no escape, and no compatibility risk.
#   Class E  stock bash 5.3 ACCEPTS it.  Meaning-changing: Bash++ claiming it
#            changes what an existing script does, so it needs a table row, a
#            near-miss fallback, and an explicit `command`/quote escape.
#
# Nothing is ever EXECUTED. Every shape is checked with `bash -n`, which parses
# and exits. That matters: several shapes in the corpus would be destructive if
# run.
#
# The second oracle is bashy's own engine. Where the two DISAGREE, bash++ is
# not the subject — that is a bash-5.3 fidelity divergence in the engine, and
# it belongs to the certification workstream. Surfacing those is a deliberate
# side effect; the corpus found one on its first run.

set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
shapes="${SHAPES:-${here}/shapes.tsv}"
baseline="${BASELINE:-${here}/baseline.tsv}"

# Reference oracles. Both are REQUIRED: a classification produced by only one
# of them would silently become an assertion again.
BASH53="${BASH53:-/opt/homebrew/bin/bash}"
BASHY="${BASHY:-${here}/../../../bashy/bin/bash}"

mode="tsv"
case "${1:-}" in
	--markdown) mode="markdown" ;;
	--check)    mode="check" ;;
	--tsv|"")   mode="tsv" ;;
	-h|--help)
		sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'
		echo
		echo "usage: classify.sh [--tsv | --markdown | --check]"
		echo "  --tsv       classification table, tab-separated (default)"
		echo "  --markdown  the Committed Start Sites table for the design doc"
		echo "  --check     ratchet: fail if any shape changed class since baseline.tsv"
		echo
		echo "env: BASH53, BASHY, SHAPES, BASELINE"
		exit 0 ;;
	*) echo "classify.sh: unknown argument: $1" >&2; exit 2 ;;
esac

die() { echo "classify.sh: $*" >&2; exit 1; }

# Fail closed. An oracle that is merely absent must never be read as agreement:
# a missing binary is the exact shape of "success by absence of evidence".
[ -f "$shapes" ] || die "shape corpus not found: $shapes"
for probe in "$BASH53" "$BASHY"; do
	[ -x "$probe" ] || die "oracle not executable: $probe (set BASH53= / BASHY=)"
done
"$BASH53" --version 2>/dev/null | head -1 | grep -q 'version 5\.3' \
	|| die "BASH53 is not a bash 5.3: $("$BASH53" --version 2>&1 | head -1)"

bash53_ver="$("$BASH53" --version | head -1)"
bashy_ver="$("$BASHY" --version | head -1)"

# parses <binary> <shape> -> 0 if the shape parses, 1 if it is a syntax error.
parses() {
	printf '%b\n' "$2" | "$1" -n 2>/dev/null
}

rows=""
total=0
disagree=0
while IFS=$'\t' read -r id phase feature shape probe; do
	case "$id" in ''|\#*) continue ;; esac
	[ -n "${shape:-}" ] || die "shape column empty for id=$id (check tabs, not spaces)"
	# A prefix that OPENS a bash compound cannot be judged standalone: `bash -n`
	# would report the missing `then`/`do`/`fi`, which is incompleteness, not
	# unavailability. Such a row supplies a 5th column — a minimal COMPLETING
	# context — and that is what the oracles actually parse. Without this,
	# `if err != nil {` looks like class R while a real script may legally
	# contain it followed by `then` on the next line, and Bash++ committing to
	# Go there would break that script.
	[ -n "${probe:-}" ] || probe="$shape"
	if parses "$BASH53" "$probe"; then b53=accept; else b53=reject; fi
	if parses "$BASHY"  "$probe"; then by=accept;  else by=reject;  fi
	if [ "$b53" = reject ]; then class=R; else class=E; fi
	if [ "$b53" = "$by" ]; then agree=yes; else agree=NO; disagree=$((disagree + 1)); fi
	rows="${rows}${id}	${phase}	${feature}	${class}	${b53}	${by}	${agree}	${shape}	${probe}
"
	total=$((total + 1))
done < "$shapes"

# A zero denominator is not a pass. It means the corpus did not load.
[ "$total" -gt 0 ] || die "classified 0 shapes — corpus empty or unreadable"

emit_tsv() {
	printf '# generated by tools/startsites/classify.sh — do not hand-edit\n'
	printf '# bash53=%s\n# bashy=%s\n' "$bash53_ver" "$bashy_ver"
	printf '# id\tphase\tfeature\tclass\tbash53\tbashy\tagree\tshape\tprobe\n'
	printf '%s' "$rows"
}

case "$mode" in
tsv)
	emit_tsv
	printf '# %d shapes: %d class R, %d class E, %d engine disagreement(s)\n' \
		"$total" \
		"$(printf '%s' "$rows" | awk -F'\t' '$4=="R"' | wc -l | tr -d ' ')" \
		"$(printf '%s' "$rows" | awk -F'\t' '$4=="E"' | wc -l | tr -d ' ')" \
		"$disagree"
	;;
markdown)
	printf '| Shape | Phase | Class | Escape / note |\n|---|---|:-:|---|\n'
	printf '%s' "$rows" | while IFS=$'\t' read -r id phase feature class b53 by agree shape probe; do
		disp="$(printf '%s' "$shape" | sed 's/\\n/ ⏎ /g; s/\\t/ /g; s/|/\\|/g')"
		if [ "$class" = R ]; then
			note='stock bash rejects — additive, no escape needed'
		else
			note='**meaning-changing** — needs `command`/quote escape'
		fi
		[ "$agree" = NO ] && note="${note}; ⚠ ENGINE DISAGREES with bash 5.3"
		printf '| `%s` | %s | %s | %s |\n' "$disp" "$phase" "$class" "$note"
	done
	;;
check)
	[ -f "$baseline" ] || die "no baseline to check against: $baseline (generate it with --tsv > baseline.tsv)"
	cur="$(mktemp)"; base="$(mktemp)"
	trap 'rm -f "$cur" "$base"' EXIT
	# Compare id+class only. Oracle VERSION lines and the shape text are
	# expected to move; a CLASS change is the thing that must never happen
	# silently, because it means the compatibility claim just changed.
	printf '%s' "$rows" | awk -F'\t' '{print $1"\t"$4}' | sort > "$cur"
	grep -v '^#' "$baseline" | awk -F'\t' 'NF{print $1"\t"$4}' | sort > "$base"
	if diff -u "$base" "$cur" > /dev/null; then
		printf 'startsites: OK — %d shapes, no class drift\n' "$total"
		[ "$disagree" -gt 0 ] && printf 'startsites: NOTE — %d engine disagreement(s); see --tsv\n' "$disagree"
		exit 0
	fi
	printf 'startsites: CLASS DRIFT — a shape changed compatibility class:\n' >&2
	diff -u "$base" "$cur" >&2 || true
	printf '\nA shape moving R->E means Bash++ would now change the meaning of an\n' >&2
	printf 'existing bash script. A shape moving E->R means an escape row is stale.\n' >&2
	printf 'Either way the design of record needs updating before this lands.\n' >&2
	exit 1
	;;
esac
